// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/deployment"
	"github.com/open-uem/ent/predicate"
)

// DeploymentUpdate is the builder for updating Deployment entities.
type DeploymentUpdate struct {
	config
	hooks     []Hook
	mutation  *DeploymentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdate) Where(ps ...predicate.Deployment) *DeploymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *DeploymentUpdate) SetPackageID(v string) *DeploymentUpdate {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillablePackageID(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeploymentUpdate) SetName(v string) *DeploymentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableName(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *DeploymentUpdate) SetVersion(v string) *DeploymentUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableVersion(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *DeploymentUpdate) ClearVersion() *DeploymentUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetInstalled sets the "installed" field.
func (_u *DeploymentUpdate) SetInstalled(v time.Time) *DeploymentUpdate {
	_u.mutation.SetInstalled(v)
	return _u
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableInstalled(v *time.Time) *DeploymentUpdate {
	if v != nil {
		_u.SetInstalled(*v)
	}
	return _u
}

// ClearInstalled clears the value of the "installed" field.
func (_u *DeploymentUpdate) ClearInstalled() *DeploymentUpdate {
	_u.mutation.ClearInstalled()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *DeploymentUpdate) SetUpdated(v time.Time) *DeploymentUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// ClearUpdated clears the value of the "updated" field.
func (_u *DeploymentUpdate) ClearUpdated() *DeploymentUpdate {
	_u.mutation.ClearUpdated()
	return _u
}

// SetFailed sets the "failed" field.
func (_u *DeploymentUpdate) SetFailed(v bool) *DeploymentUpdate {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableFailed(v *bool) *DeploymentUpdate {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// ClearFailed clears the value of the "failed" field.
func (_u *DeploymentUpdate) ClearFailed() *DeploymentUpdate {
	_u.mutation.ClearFailed()
	return _u
}

// SetByProfile sets the "by_profile" field.
func (_u *DeploymentUpdate) SetByProfile(v bool) *DeploymentUpdate {
	_u.mutation.SetByProfile(v)
	return _u
}

// SetNillableByProfile sets the "by_profile" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableByProfile(v *bool) *DeploymentUpdate {
	if v != nil {
		_u.SetByProfile(*v)
	}
	return _u
}

// ClearByProfile clears the value of the "by_profile" field.
func (_u *DeploymentUpdate) ClearByProfile() *DeploymentUpdate {
	_u.mutation.ClearByProfile()
	return _u
}

// SetMoreInfo sets the "more_info" field.
func (_u *DeploymentUpdate) SetMoreInfo(v string) *DeploymentUpdate {
	_u.mutation.SetMoreInfo(v)
	return _u
}

// SetNillableMoreInfo sets the "more_info" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableMoreInfo(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetMoreInfo(*v)
	}
	return _u
}

// ClearMoreInfo clears the value of the "more_info" field.
func (_u *DeploymentUpdate) ClearMoreInfo() *DeploymentUpdate {
	_u.mutation.ClearMoreInfo()
	return _u
}

// SetOwnerID sets the "owner" edge to the Agent entity by ID.
func (_u *DeploymentUpdate) SetOwnerID(id string) *DeploymentUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Agent entity.
func (_u *DeploymentUpdate) SetOwner(v *Agent) *DeploymentUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdate) Mutation() *DeploymentMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Agent entity.
func (_u *DeploymentUpdate) ClearOwner() *DeploymentUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeploymentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeploymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeploymentUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok && !_u.mutation.UpdatedCleared() {
		v := deployment.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentUpdate) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeploymentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeploymentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeploymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(deployment.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deployment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(deployment.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(deployment.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Installed(); ok {
		_spec.SetField(deployment.FieldInstalled, field.TypeTime, value)
	}
	if _u.mutation.InstalledCleared() {
		_spec.ClearField(deployment.FieldInstalled, field.TypeTime)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(deployment.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UpdatedCleared() {
		_spec.ClearField(deployment.FieldUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(deployment.FieldFailed, field.TypeBool, value)
	}
	if _u.mutation.FailedCleared() {
		_spec.ClearField(deployment.FieldFailed, field.TypeBool)
	}
	if value, ok := _u.mutation.ByProfile(); ok {
		_spec.SetField(deployment.FieldByProfile, field.TypeBool, value)
	}
	if _u.mutation.ByProfileCleared() {
		_spec.ClearField(deployment.FieldByProfile, field.TypeBool)
	}
	if value, ok := _u.mutation.MoreInfo(); ok {
		_spec.SetField(deployment.FieldMoreInfo, field.TypeString, value)
	}
	if _u.mutation.MoreInfoCleared() {
		_spec.ClearField(deployment.FieldMoreInfo, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.OwnerTable,
			Columns: []string{deployment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.OwnerTable,
			Columns: []string{deployment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeploymentUpdateOne is the builder for updating a single Deployment entity.
type DeploymentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeploymentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetPackageID sets the "package_id" field.
func (_u *DeploymentUpdateOne) SetPackageID(v string) *DeploymentUpdateOne {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillablePackageID(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeploymentUpdateOne) SetName(v string) *DeploymentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableName(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *DeploymentUpdateOne) SetVersion(v string) *DeploymentUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableVersion(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *DeploymentUpdateOne) ClearVersion() *DeploymentUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetInstalled sets the "installed" field.
func (_u *DeploymentUpdateOne) SetInstalled(v time.Time) *DeploymentUpdateOne {
	_u.mutation.SetInstalled(v)
	return _u
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableInstalled(v *time.Time) *DeploymentUpdateOne {
	if v != nil {
		_u.SetInstalled(*v)
	}
	return _u
}

// ClearInstalled clears the value of the "installed" field.
func (_u *DeploymentUpdateOne) ClearInstalled() *DeploymentUpdateOne {
	_u.mutation.ClearInstalled()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *DeploymentUpdateOne) SetUpdated(v time.Time) *DeploymentUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// ClearUpdated clears the value of the "updated" field.
func (_u *DeploymentUpdateOne) ClearUpdated() *DeploymentUpdateOne {
	_u.mutation.ClearUpdated()
	return _u
}

// SetFailed sets the "failed" field.
func (_u *DeploymentUpdateOne) SetFailed(v bool) *DeploymentUpdateOne {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableFailed(v *bool) *DeploymentUpdateOne {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// ClearFailed clears the value of the "failed" field.
func (_u *DeploymentUpdateOne) ClearFailed() *DeploymentUpdateOne {
	_u.mutation.ClearFailed()
	return _u
}

// SetByProfile sets the "by_profile" field.
func (_u *DeploymentUpdateOne) SetByProfile(v bool) *DeploymentUpdateOne {
	_u.mutation.SetByProfile(v)
	return _u
}

// SetNillableByProfile sets the "by_profile" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableByProfile(v *bool) *DeploymentUpdateOne {
	if v != nil {
		_u.SetByProfile(*v)
	}
	return _u
}

// ClearByProfile clears the value of the "by_profile" field.
func (_u *DeploymentUpdateOne) ClearByProfile() *DeploymentUpdateOne {
	_u.mutation.ClearByProfile()
	return _u
}

// SetMoreInfo sets the "more_info" field.
func (_u *DeploymentUpdateOne) SetMoreInfo(v string) *DeploymentUpdateOne {
	_u.mutation.SetMoreInfo(v)
	return _u
}

// SetNillableMoreInfo sets the "more_info" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableMoreInfo(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetMoreInfo(*v)
	}
	return _u
}

// ClearMoreInfo clears the value of the "more_info" field.
func (_u *DeploymentUpdateOne) ClearMoreInfo() *DeploymentUpdateOne {
	_u.mutation.ClearMoreInfo()
	return _u
}

// SetOwnerID sets the "owner" edge to the Agent entity by ID.
func (_u *DeploymentUpdateOne) SetOwnerID(id string) *DeploymentUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Agent entity.
func (_u *DeploymentUpdateOne) SetOwner(v *Agent) *DeploymentUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdateOne) Mutation() *DeploymentMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Agent entity.
func (_u *DeploymentUpdateOne) ClearOwner() *DeploymentUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdateOne) Where(ps ...predicate.Deployment) *DeploymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeploymentUpdateOne) Select(field string, fields ...string) *DeploymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deployment entity.
func (_u *DeploymentUpdateOne) Save(ctx context.Context) (*Deployment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdateOne) SaveX(ctx context.Context) *Deployment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeploymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeploymentUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok && !_u.mutation.UpdatedCleared() {
		v := deployment.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentUpdateOne) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeploymentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeploymentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeploymentUpdateOne) sqlSave(ctx context.Context) (_node *Deployment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deployment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deployment.FieldID)
		for _, f := range fields {
			if !deployment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deployment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(deployment.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deployment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(deployment.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(deployment.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Installed(); ok {
		_spec.SetField(deployment.FieldInstalled, field.TypeTime, value)
	}
	if _u.mutation.InstalledCleared() {
		_spec.ClearField(deployment.FieldInstalled, field.TypeTime)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(deployment.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UpdatedCleared() {
		_spec.ClearField(deployment.FieldUpdated, field.TypeTime)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(deployment.FieldFailed, field.TypeBool, value)
	}
	if _u.mutation.FailedCleared() {
		_spec.ClearField(deployment.FieldFailed, field.TypeBool)
	}
	if value, ok := _u.mutation.ByProfile(); ok {
		_spec.SetField(deployment.FieldByProfile, field.TypeBool, value)
	}
	if _u.mutation.ByProfileCleared() {
		_spec.ClearField(deployment.FieldByProfile, field.TypeBool)
	}
	if value, ok := _u.mutation.MoreInfo(); ok {
		_spec.SetField(deployment.FieldMoreInfo, field.TypeString, value)
	}
	if _u.mutation.MoreInfoCleared() {
		_spec.ClearField(deployment.FieldMoreInfo, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.OwnerTable,
			Columns: []string{deployment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.OwnerTable,
			Columns: []string{deployment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Deployment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
