// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/logicaldisk"
	"github.com/open-uem/ent/predicate"
)

// LogicalDiskUpdate is the builder for updating LogicalDisk entities.
type LogicalDiskUpdate struct {
	config
	hooks     []Hook
	mutation  *LogicalDiskMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LogicalDiskUpdate builder.
func (ldu *LogicalDiskUpdate) Where(ps ...predicate.LogicalDisk) *LogicalDiskUpdate {
	ldu.mutation.Where(ps...)
	return ldu
}

// SetLabel sets the "label" field.
func (ldu *LogicalDiskUpdate) SetLabel(s string) *LogicalDiskUpdate {
	ldu.mutation.SetLabel(s)
	return ldu
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableLabel(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetLabel(*s)
	}
	return ldu
}

// SetFilesystem sets the "filesystem" field.
func (ldu *LogicalDiskUpdate) SetFilesystem(s string) *LogicalDiskUpdate {
	ldu.mutation.SetFilesystem(s)
	return ldu
}

// SetNillableFilesystem sets the "filesystem" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableFilesystem(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetFilesystem(*s)
	}
	return ldu
}

// ClearFilesystem clears the value of the "filesystem" field.
func (ldu *LogicalDiskUpdate) ClearFilesystem() *LogicalDiskUpdate {
	ldu.mutation.ClearFilesystem()
	return ldu
}

// SetUsage sets the "usage" field.
func (ldu *LogicalDiskUpdate) SetUsage(i int8) *LogicalDiskUpdate {
	ldu.mutation.ResetUsage()
	ldu.mutation.SetUsage(i)
	return ldu
}

// SetNillableUsage sets the "usage" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableUsage(i *int8) *LogicalDiskUpdate {
	if i != nil {
		ldu.SetUsage(*i)
	}
	return ldu
}

// AddUsage adds i to the "usage" field.
func (ldu *LogicalDiskUpdate) AddUsage(i int8) *LogicalDiskUpdate {
	ldu.mutation.AddUsage(i)
	return ldu
}

// SetSizeInUnits sets the "size_in_units" field.
func (ldu *LogicalDiskUpdate) SetSizeInUnits(s string) *LogicalDiskUpdate {
	ldu.mutation.SetSizeInUnits(s)
	return ldu
}

// SetNillableSizeInUnits sets the "size_in_units" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableSizeInUnits(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetSizeInUnits(*s)
	}
	return ldu
}

// ClearSizeInUnits clears the value of the "size_in_units" field.
func (ldu *LogicalDiskUpdate) ClearSizeInUnits() *LogicalDiskUpdate {
	ldu.mutation.ClearSizeInUnits()
	return ldu
}

// SetRemainingSpaceInUnits sets the "remaining_space_in_units" field.
func (ldu *LogicalDiskUpdate) SetRemainingSpaceInUnits(s string) *LogicalDiskUpdate {
	ldu.mutation.SetRemainingSpaceInUnits(s)
	return ldu
}

// SetNillableRemainingSpaceInUnits sets the "remaining_space_in_units" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableRemainingSpaceInUnits(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetRemainingSpaceInUnits(*s)
	}
	return ldu
}

// ClearRemainingSpaceInUnits clears the value of the "remaining_space_in_units" field.
func (ldu *LogicalDiskUpdate) ClearRemainingSpaceInUnits() *LogicalDiskUpdate {
	ldu.mutation.ClearRemainingSpaceInUnits()
	return ldu
}

// SetVolumeName sets the "volume_name" field.
func (ldu *LogicalDiskUpdate) SetVolumeName(s string) *LogicalDiskUpdate {
	ldu.mutation.SetVolumeName(s)
	return ldu
}

// SetNillableVolumeName sets the "volume_name" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableVolumeName(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetVolumeName(*s)
	}
	return ldu
}

// ClearVolumeName clears the value of the "volume_name" field.
func (ldu *LogicalDiskUpdate) ClearVolumeName() *LogicalDiskUpdate {
	ldu.mutation.ClearVolumeName()
	return ldu
}

// SetBitlockerStatus sets the "bitlocker_status" field.
func (ldu *LogicalDiskUpdate) SetBitlockerStatus(s string) *LogicalDiskUpdate {
	ldu.mutation.SetBitlockerStatus(s)
	return ldu
}

// SetNillableBitlockerStatus sets the "bitlocker_status" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerStatus(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetBitlockerStatus(*s)
	}
	return ldu
}

// ClearBitlockerStatus clears the value of the "bitlocker_status" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerStatus() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerStatus()
	return ldu
}

// SetVolumeType sets the "volume_type" field.
func (ldu *LogicalDiskUpdate) SetVolumeType(u uint32) *LogicalDiskUpdate {
	ldu.mutation.ResetVolumeType()
	ldu.mutation.SetVolumeType(u)
	return ldu
}

// SetNillableVolumeType sets the "volume_type" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableVolumeType(u *uint32) *LogicalDiskUpdate {
	if u != nil {
		ldu.SetVolumeType(*u)
	}
	return ldu
}

// AddVolumeType adds u to the "volume_type" field.
func (ldu *LogicalDiskUpdate) AddVolumeType(u int32) *LogicalDiskUpdate {
	ldu.mutation.AddVolumeType(u)
	return ldu
}

// ClearVolumeType clears the value of the "volume_type" field.
func (ldu *LogicalDiskUpdate) ClearVolumeType() *LogicalDiskUpdate {
	ldu.mutation.ClearVolumeType()
	return ldu
}

// SetBitlockerConversionStatus sets the "bitlocker_conversion_status" field.
func (ldu *LogicalDiskUpdate) SetBitlockerConversionStatus(i int32) *LogicalDiskUpdate {
	ldu.mutation.ResetBitlockerConversionStatus()
	ldu.mutation.SetBitlockerConversionStatus(i)
	return ldu
}

// SetNillableBitlockerConversionStatus sets the "bitlocker_conversion_status" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerConversionStatus(i *int32) *LogicalDiskUpdate {
	if i != nil {
		ldu.SetBitlockerConversionStatus(*i)
	}
	return ldu
}

// AddBitlockerConversionStatus adds i to the "bitlocker_conversion_status" field.
func (ldu *LogicalDiskUpdate) AddBitlockerConversionStatus(i int32) *LogicalDiskUpdate {
	ldu.mutation.AddBitlockerConversionStatus(i)
	return ldu
}

// ClearBitlockerConversionStatus clears the value of the "bitlocker_conversion_status" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerConversionStatus() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerConversionStatus()
	return ldu
}

// SetBitlockerEncryptionPercentage sets the "bitlocker_encryption_percentage" field.
func (ldu *LogicalDiskUpdate) SetBitlockerEncryptionPercentage(i int32) *LogicalDiskUpdate {
	ldu.mutation.ResetBitlockerEncryptionPercentage()
	ldu.mutation.SetBitlockerEncryptionPercentage(i)
	return ldu
}

// SetNillableBitlockerEncryptionPercentage sets the "bitlocker_encryption_percentage" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerEncryptionPercentage(i *int32) *LogicalDiskUpdate {
	if i != nil {
		ldu.SetBitlockerEncryptionPercentage(*i)
	}
	return ldu
}

// AddBitlockerEncryptionPercentage adds i to the "bitlocker_encryption_percentage" field.
func (ldu *LogicalDiskUpdate) AddBitlockerEncryptionPercentage(i int32) *LogicalDiskUpdate {
	ldu.mutation.AddBitlockerEncryptionPercentage(i)
	return ldu
}

// ClearBitlockerEncryptionPercentage clears the value of the "bitlocker_encryption_percentage" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerEncryptionPercentage() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerEncryptionPercentage()
	return ldu
}

// SetBitlockerRecoveryKey sets the "bitlocker_recovery_key" field.
func (ldu *LogicalDiskUpdate) SetBitlockerRecoveryKey(s string) *LogicalDiskUpdate {
	ldu.mutation.SetBitlockerRecoveryKey(s)
	return ldu
}

// SetNillableBitlockerRecoveryKey sets the "bitlocker_recovery_key" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerRecoveryKey(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetBitlockerRecoveryKey(*s)
	}
	return ldu
}

// ClearBitlockerRecoveryKey clears the value of the "bitlocker_recovery_key" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerRecoveryKey() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerRecoveryKey()
	return ldu
}

// SetBitlockerOperationInProgress sets the "bitlocker_operation_in_progress" field.
func (ldu *LogicalDiskUpdate) SetBitlockerOperationInProgress(s string) *LogicalDiskUpdate {
	ldu.mutation.SetBitlockerOperationInProgress(s)
	return ldu
}

// SetNillableBitlockerOperationInProgress sets the "bitlocker_operation_in_progress" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerOperationInProgress(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetBitlockerOperationInProgress(*s)
	}
	return ldu
}

// ClearBitlockerOperationInProgress clears the value of the "bitlocker_operation_in_progress" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerOperationInProgress() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerOperationInProgress()
	return ldu
}

// SetBitlockerOperationResult sets the "bitlocker_operation_result" field.
func (ldu *LogicalDiskUpdate) SetBitlockerOperationResult(s string) *LogicalDiskUpdate {
	ldu.mutation.SetBitlockerOperationResult(s)
	return ldu
}

// SetNillableBitlockerOperationResult sets the "bitlocker_operation_result" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerOperationResult(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetBitlockerOperationResult(*s)
	}
	return ldu
}

// ClearBitlockerOperationResult clears the value of the "bitlocker_operation_result" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerOperationResult() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerOperationResult()
	return ldu
}

// SetBitlockerIsAutoUnlockEnabled sets the "bitlocker_is_auto_unlock_enabled" field.
func (ldu *LogicalDiskUpdate) SetBitlockerIsAutoUnlockEnabled(b bool) *LogicalDiskUpdate {
	ldu.mutation.SetBitlockerIsAutoUnlockEnabled(b)
	return ldu
}

// SetNillableBitlockerIsAutoUnlockEnabled sets the "bitlocker_is_auto_unlock_enabled" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerIsAutoUnlockEnabled(b *bool) *LogicalDiskUpdate {
	if b != nil {
		ldu.SetBitlockerIsAutoUnlockEnabled(*b)
	}
	return ldu
}

// ClearBitlockerIsAutoUnlockEnabled clears the value of the "bitlocker_is_auto_unlock_enabled" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerIsAutoUnlockEnabled() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerIsAutoUnlockEnabled()
	return ldu
}

// SetBitlockerVolumeKeyProtectorID sets the "bitlocker_volume_key_protector_id" field.
func (ldu *LogicalDiskUpdate) SetBitlockerVolumeKeyProtectorID(s string) *LogicalDiskUpdate {
	ldu.mutation.SetBitlockerVolumeKeyProtectorID(s)
	return ldu
}

// SetNillableBitlockerVolumeKeyProtectorID sets the "bitlocker_volume_key_protector_id" field if the given value is not nil.
func (ldu *LogicalDiskUpdate) SetNillableBitlockerVolumeKeyProtectorID(s *string) *LogicalDiskUpdate {
	if s != nil {
		ldu.SetBitlockerVolumeKeyProtectorID(*s)
	}
	return ldu
}

// ClearBitlockerVolumeKeyProtectorID clears the value of the "bitlocker_volume_key_protector_id" field.
func (ldu *LogicalDiskUpdate) ClearBitlockerVolumeKeyProtectorID() *LogicalDiskUpdate {
	ldu.mutation.ClearBitlockerVolumeKeyProtectorID()
	return ldu
}

// SetOwnerID sets the "owner" edge to the Agent entity by ID.
func (ldu *LogicalDiskUpdate) SetOwnerID(id string) *LogicalDiskUpdate {
	ldu.mutation.SetOwnerID(id)
	return ldu
}

// SetOwner sets the "owner" edge to the Agent entity.
func (ldu *LogicalDiskUpdate) SetOwner(a *Agent) *LogicalDiskUpdate {
	return ldu.SetOwnerID(a.ID)
}

// Mutation returns the LogicalDiskMutation object of the builder.
func (ldu *LogicalDiskUpdate) Mutation() *LogicalDiskMutation {
	return ldu.mutation
}

// ClearOwner clears the "owner" edge to the Agent entity.
func (ldu *LogicalDiskUpdate) ClearOwner() *LogicalDiskUpdate {
	ldu.mutation.ClearOwner()
	return ldu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ldu *LogicalDiskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ldu.sqlSave, ldu.mutation, ldu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ldu *LogicalDiskUpdate) SaveX(ctx context.Context) int {
	affected, err := ldu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ldu *LogicalDiskUpdate) Exec(ctx context.Context) error {
	_, err := ldu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ldu *LogicalDiskUpdate) ExecX(ctx context.Context) {
	if err := ldu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ldu *LogicalDiskUpdate) check() error {
	if ldu.mutation.OwnerCleared() && len(ldu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LogicalDisk.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ldu *LogicalDiskUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LogicalDiskUpdate {
	ldu.modifiers = append(ldu.modifiers, modifiers...)
	return ldu
}

func (ldu *LogicalDiskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ldu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(logicaldisk.Table, logicaldisk.Columns, sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt))
	if ps := ldu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ldu.mutation.Label(); ok {
		_spec.SetField(logicaldisk.FieldLabel, field.TypeString, value)
	}
	if value, ok := ldu.mutation.Filesystem(); ok {
		_spec.SetField(logicaldisk.FieldFilesystem, field.TypeString, value)
	}
	if ldu.mutation.FilesystemCleared() {
		_spec.ClearField(logicaldisk.FieldFilesystem, field.TypeString)
	}
	if value, ok := ldu.mutation.Usage(); ok {
		_spec.SetField(logicaldisk.FieldUsage, field.TypeInt8, value)
	}
	if value, ok := ldu.mutation.AddedUsage(); ok {
		_spec.AddField(logicaldisk.FieldUsage, field.TypeInt8, value)
	}
	if value, ok := ldu.mutation.SizeInUnits(); ok {
		_spec.SetField(logicaldisk.FieldSizeInUnits, field.TypeString, value)
	}
	if ldu.mutation.SizeInUnitsCleared() {
		_spec.ClearField(logicaldisk.FieldSizeInUnits, field.TypeString)
	}
	if value, ok := ldu.mutation.RemainingSpaceInUnits(); ok {
		_spec.SetField(logicaldisk.FieldRemainingSpaceInUnits, field.TypeString, value)
	}
	if ldu.mutation.RemainingSpaceInUnitsCleared() {
		_spec.ClearField(logicaldisk.FieldRemainingSpaceInUnits, field.TypeString)
	}
	if value, ok := ldu.mutation.VolumeName(); ok {
		_spec.SetField(logicaldisk.FieldVolumeName, field.TypeString, value)
	}
	if ldu.mutation.VolumeNameCleared() {
		_spec.ClearField(logicaldisk.FieldVolumeName, field.TypeString)
	}
	if value, ok := ldu.mutation.BitlockerStatus(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerStatus, field.TypeString, value)
	}
	if ldu.mutation.BitlockerStatusCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerStatus, field.TypeString)
	}
	if value, ok := ldu.mutation.VolumeType(); ok {
		_spec.SetField(logicaldisk.FieldVolumeType, field.TypeUint32, value)
	}
	if value, ok := ldu.mutation.AddedVolumeType(); ok {
		_spec.AddField(logicaldisk.FieldVolumeType, field.TypeUint32, value)
	}
	if ldu.mutation.VolumeTypeCleared() {
		_spec.ClearField(logicaldisk.FieldVolumeType, field.TypeUint32)
	}
	if value, ok := ldu.mutation.BitlockerConversionStatus(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerConversionStatus, field.TypeInt32, value)
	}
	if value, ok := ldu.mutation.AddedBitlockerConversionStatus(); ok {
		_spec.AddField(logicaldisk.FieldBitlockerConversionStatus, field.TypeInt32, value)
	}
	if ldu.mutation.BitlockerConversionStatusCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerConversionStatus, field.TypeInt32)
	}
	if value, ok := ldu.mutation.BitlockerEncryptionPercentage(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerEncryptionPercentage, field.TypeInt32, value)
	}
	if value, ok := ldu.mutation.AddedBitlockerEncryptionPercentage(); ok {
		_spec.AddField(logicaldisk.FieldBitlockerEncryptionPercentage, field.TypeInt32, value)
	}
	if ldu.mutation.BitlockerEncryptionPercentageCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerEncryptionPercentage, field.TypeInt32)
	}
	if value, ok := ldu.mutation.BitlockerRecoveryKey(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerRecoveryKey, field.TypeString, value)
	}
	if ldu.mutation.BitlockerRecoveryKeyCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerRecoveryKey, field.TypeString)
	}
	if value, ok := ldu.mutation.BitlockerOperationInProgress(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerOperationInProgress, field.TypeString, value)
	}
	if ldu.mutation.BitlockerOperationInProgressCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerOperationInProgress, field.TypeString)
	}
	if value, ok := ldu.mutation.BitlockerOperationResult(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerOperationResult, field.TypeString, value)
	}
	if ldu.mutation.BitlockerOperationResultCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerOperationResult, field.TypeString)
	}
	if value, ok := ldu.mutation.BitlockerIsAutoUnlockEnabled(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerIsAutoUnlockEnabled, field.TypeBool, value)
	}
	if ldu.mutation.BitlockerIsAutoUnlockEnabledCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerIsAutoUnlockEnabled, field.TypeBool)
	}
	if value, ok := ldu.mutation.BitlockerVolumeKeyProtectorID(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerVolumeKeyProtectorID, field.TypeString, value)
	}
	if ldu.mutation.BitlockerVolumeKeyProtectorIDCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerVolumeKeyProtectorID, field.TypeString)
	}
	if ldu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logicaldisk.OwnerTable,
			Columns: []string{logicaldisk.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ldu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logicaldisk.OwnerTable,
			Columns: []string{logicaldisk.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ldu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ldu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logicaldisk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ldu.mutation.done = true
	return n, nil
}

// LogicalDiskUpdateOne is the builder for updating a single LogicalDisk entity.
type LogicalDiskUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LogicalDiskMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetLabel sets the "label" field.
func (lduo *LogicalDiskUpdateOne) SetLabel(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetLabel(s)
	return lduo
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableLabel(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetLabel(*s)
	}
	return lduo
}

// SetFilesystem sets the "filesystem" field.
func (lduo *LogicalDiskUpdateOne) SetFilesystem(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetFilesystem(s)
	return lduo
}

// SetNillableFilesystem sets the "filesystem" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableFilesystem(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetFilesystem(*s)
	}
	return lduo
}

// ClearFilesystem clears the value of the "filesystem" field.
func (lduo *LogicalDiskUpdateOne) ClearFilesystem() *LogicalDiskUpdateOne {
	lduo.mutation.ClearFilesystem()
	return lduo
}

// SetUsage sets the "usage" field.
func (lduo *LogicalDiskUpdateOne) SetUsage(i int8) *LogicalDiskUpdateOne {
	lduo.mutation.ResetUsage()
	lduo.mutation.SetUsage(i)
	return lduo
}

// SetNillableUsage sets the "usage" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableUsage(i *int8) *LogicalDiskUpdateOne {
	if i != nil {
		lduo.SetUsage(*i)
	}
	return lduo
}

// AddUsage adds i to the "usage" field.
func (lduo *LogicalDiskUpdateOne) AddUsage(i int8) *LogicalDiskUpdateOne {
	lduo.mutation.AddUsage(i)
	return lduo
}

// SetSizeInUnits sets the "size_in_units" field.
func (lduo *LogicalDiskUpdateOne) SetSizeInUnits(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetSizeInUnits(s)
	return lduo
}

// SetNillableSizeInUnits sets the "size_in_units" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableSizeInUnits(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetSizeInUnits(*s)
	}
	return lduo
}

// ClearSizeInUnits clears the value of the "size_in_units" field.
func (lduo *LogicalDiskUpdateOne) ClearSizeInUnits() *LogicalDiskUpdateOne {
	lduo.mutation.ClearSizeInUnits()
	return lduo
}

// SetRemainingSpaceInUnits sets the "remaining_space_in_units" field.
func (lduo *LogicalDiskUpdateOne) SetRemainingSpaceInUnits(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetRemainingSpaceInUnits(s)
	return lduo
}

// SetNillableRemainingSpaceInUnits sets the "remaining_space_in_units" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableRemainingSpaceInUnits(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetRemainingSpaceInUnits(*s)
	}
	return lduo
}

// ClearRemainingSpaceInUnits clears the value of the "remaining_space_in_units" field.
func (lduo *LogicalDiskUpdateOne) ClearRemainingSpaceInUnits() *LogicalDiskUpdateOne {
	lduo.mutation.ClearRemainingSpaceInUnits()
	return lduo
}

// SetVolumeName sets the "volume_name" field.
func (lduo *LogicalDiskUpdateOne) SetVolumeName(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetVolumeName(s)
	return lduo
}

// SetNillableVolumeName sets the "volume_name" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableVolumeName(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetVolumeName(*s)
	}
	return lduo
}

// ClearVolumeName clears the value of the "volume_name" field.
func (lduo *LogicalDiskUpdateOne) ClearVolumeName() *LogicalDiskUpdateOne {
	lduo.mutation.ClearVolumeName()
	return lduo
}

// SetBitlockerStatus sets the "bitlocker_status" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerStatus(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetBitlockerStatus(s)
	return lduo
}

// SetNillableBitlockerStatus sets the "bitlocker_status" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerStatus(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetBitlockerStatus(*s)
	}
	return lduo
}

// ClearBitlockerStatus clears the value of the "bitlocker_status" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerStatus() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerStatus()
	return lduo
}

// SetVolumeType sets the "volume_type" field.
func (lduo *LogicalDiskUpdateOne) SetVolumeType(u uint32) *LogicalDiskUpdateOne {
	lduo.mutation.ResetVolumeType()
	lduo.mutation.SetVolumeType(u)
	return lduo
}

// SetNillableVolumeType sets the "volume_type" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableVolumeType(u *uint32) *LogicalDiskUpdateOne {
	if u != nil {
		lduo.SetVolumeType(*u)
	}
	return lduo
}

// AddVolumeType adds u to the "volume_type" field.
func (lduo *LogicalDiskUpdateOne) AddVolumeType(u int32) *LogicalDiskUpdateOne {
	lduo.mutation.AddVolumeType(u)
	return lduo
}

// ClearVolumeType clears the value of the "volume_type" field.
func (lduo *LogicalDiskUpdateOne) ClearVolumeType() *LogicalDiskUpdateOne {
	lduo.mutation.ClearVolumeType()
	return lduo
}

// SetBitlockerConversionStatus sets the "bitlocker_conversion_status" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerConversionStatus(i int32) *LogicalDiskUpdateOne {
	lduo.mutation.ResetBitlockerConversionStatus()
	lduo.mutation.SetBitlockerConversionStatus(i)
	return lduo
}

// SetNillableBitlockerConversionStatus sets the "bitlocker_conversion_status" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerConversionStatus(i *int32) *LogicalDiskUpdateOne {
	if i != nil {
		lduo.SetBitlockerConversionStatus(*i)
	}
	return lduo
}

// AddBitlockerConversionStatus adds i to the "bitlocker_conversion_status" field.
func (lduo *LogicalDiskUpdateOne) AddBitlockerConversionStatus(i int32) *LogicalDiskUpdateOne {
	lduo.mutation.AddBitlockerConversionStatus(i)
	return lduo
}

// ClearBitlockerConversionStatus clears the value of the "bitlocker_conversion_status" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerConversionStatus() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerConversionStatus()
	return lduo
}

// SetBitlockerEncryptionPercentage sets the "bitlocker_encryption_percentage" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerEncryptionPercentage(i int32) *LogicalDiskUpdateOne {
	lduo.mutation.ResetBitlockerEncryptionPercentage()
	lduo.mutation.SetBitlockerEncryptionPercentage(i)
	return lduo
}

// SetNillableBitlockerEncryptionPercentage sets the "bitlocker_encryption_percentage" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerEncryptionPercentage(i *int32) *LogicalDiskUpdateOne {
	if i != nil {
		lduo.SetBitlockerEncryptionPercentage(*i)
	}
	return lduo
}

// AddBitlockerEncryptionPercentage adds i to the "bitlocker_encryption_percentage" field.
func (lduo *LogicalDiskUpdateOne) AddBitlockerEncryptionPercentage(i int32) *LogicalDiskUpdateOne {
	lduo.mutation.AddBitlockerEncryptionPercentage(i)
	return lduo
}

// ClearBitlockerEncryptionPercentage clears the value of the "bitlocker_encryption_percentage" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerEncryptionPercentage() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerEncryptionPercentage()
	return lduo
}

// SetBitlockerRecoveryKey sets the "bitlocker_recovery_key" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerRecoveryKey(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetBitlockerRecoveryKey(s)
	return lduo
}

// SetNillableBitlockerRecoveryKey sets the "bitlocker_recovery_key" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerRecoveryKey(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetBitlockerRecoveryKey(*s)
	}
	return lduo
}

// ClearBitlockerRecoveryKey clears the value of the "bitlocker_recovery_key" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerRecoveryKey() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerRecoveryKey()
	return lduo
}

// SetBitlockerOperationInProgress sets the "bitlocker_operation_in_progress" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerOperationInProgress(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetBitlockerOperationInProgress(s)
	return lduo
}

// SetNillableBitlockerOperationInProgress sets the "bitlocker_operation_in_progress" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerOperationInProgress(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetBitlockerOperationInProgress(*s)
	}
	return lduo
}

// ClearBitlockerOperationInProgress clears the value of the "bitlocker_operation_in_progress" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerOperationInProgress() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerOperationInProgress()
	return lduo
}

// SetBitlockerOperationResult sets the "bitlocker_operation_result" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerOperationResult(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetBitlockerOperationResult(s)
	return lduo
}

// SetNillableBitlockerOperationResult sets the "bitlocker_operation_result" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerOperationResult(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetBitlockerOperationResult(*s)
	}
	return lduo
}

// ClearBitlockerOperationResult clears the value of the "bitlocker_operation_result" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerOperationResult() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerOperationResult()
	return lduo
}

// SetBitlockerIsAutoUnlockEnabled sets the "bitlocker_is_auto_unlock_enabled" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerIsAutoUnlockEnabled(b bool) *LogicalDiskUpdateOne {
	lduo.mutation.SetBitlockerIsAutoUnlockEnabled(b)
	return lduo
}

// SetNillableBitlockerIsAutoUnlockEnabled sets the "bitlocker_is_auto_unlock_enabled" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerIsAutoUnlockEnabled(b *bool) *LogicalDiskUpdateOne {
	if b != nil {
		lduo.SetBitlockerIsAutoUnlockEnabled(*b)
	}
	return lduo
}

// ClearBitlockerIsAutoUnlockEnabled clears the value of the "bitlocker_is_auto_unlock_enabled" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerIsAutoUnlockEnabled() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerIsAutoUnlockEnabled()
	return lduo
}

// SetBitlockerVolumeKeyProtectorID sets the "bitlocker_volume_key_protector_id" field.
func (lduo *LogicalDiskUpdateOne) SetBitlockerVolumeKeyProtectorID(s string) *LogicalDiskUpdateOne {
	lduo.mutation.SetBitlockerVolumeKeyProtectorID(s)
	return lduo
}

// SetNillableBitlockerVolumeKeyProtectorID sets the "bitlocker_volume_key_protector_id" field if the given value is not nil.
func (lduo *LogicalDiskUpdateOne) SetNillableBitlockerVolumeKeyProtectorID(s *string) *LogicalDiskUpdateOne {
	if s != nil {
		lduo.SetBitlockerVolumeKeyProtectorID(*s)
	}
	return lduo
}

// ClearBitlockerVolumeKeyProtectorID clears the value of the "bitlocker_volume_key_protector_id" field.
func (lduo *LogicalDiskUpdateOne) ClearBitlockerVolumeKeyProtectorID() *LogicalDiskUpdateOne {
	lduo.mutation.ClearBitlockerVolumeKeyProtectorID()
	return lduo
}

// SetOwnerID sets the "owner" edge to the Agent entity by ID.
func (lduo *LogicalDiskUpdateOne) SetOwnerID(id string) *LogicalDiskUpdateOne {
	lduo.mutation.SetOwnerID(id)
	return lduo
}

// SetOwner sets the "owner" edge to the Agent entity.
func (lduo *LogicalDiskUpdateOne) SetOwner(a *Agent) *LogicalDiskUpdateOne {
	return lduo.SetOwnerID(a.ID)
}

// Mutation returns the LogicalDiskMutation object of the builder.
func (lduo *LogicalDiskUpdateOne) Mutation() *LogicalDiskMutation {
	return lduo.mutation
}

// ClearOwner clears the "owner" edge to the Agent entity.
func (lduo *LogicalDiskUpdateOne) ClearOwner() *LogicalDiskUpdateOne {
	lduo.mutation.ClearOwner()
	return lduo
}

// Where appends a list predicates to the LogicalDiskUpdate builder.
func (lduo *LogicalDiskUpdateOne) Where(ps ...predicate.LogicalDisk) *LogicalDiskUpdateOne {
	lduo.mutation.Where(ps...)
	return lduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lduo *LogicalDiskUpdateOne) Select(field string, fields ...string) *LogicalDiskUpdateOne {
	lduo.fields = append([]string{field}, fields...)
	return lduo
}

// Save executes the query and returns the updated LogicalDisk entity.
func (lduo *LogicalDiskUpdateOne) Save(ctx context.Context) (*LogicalDisk, error) {
	return withHooks(ctx, lduo.sqlSave, lduo.mutation, lduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lduo *LogicalDiskUpdateOne) SaveX(ctx context.Context) *LogicalDisk {
	node, err := lduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lduo *LogicalDiskUpdateOne) Exec(ctx context.Context) error {
	_, err := lduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lduo *LogicalDiskUpdateOne) ExecX(ctx context.Context) {
	if err := lduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lduo *LogicalDiskUpdateOne) check() error {
	if lduo.mutation.OwnerCleared() && len(lduo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LogicalDisk.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lduo *LogicalDiskUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LogicalDiskUpdateOne {
	lduo.modifiers = append(lduo.modifiers, modifiers...)
	return lduo
}

func (lduo *LogicalDiskUpdateOne) sqlSave(ctx context.Context) (_node *LogicalDisk, err error) {
	if err := lduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(logicaldisk.Table, logicaldisk.Columns, sqlgraph.NewFieldSpec(logicaldisk.FieldID, field.TypeInt))
	id, ok := lduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LogicalDisk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logicaldisk.FieldID)
		for _, f := range fields {
			if !logicaldisk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != logicaldisk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lduo.mutation.Label(); ok {
		_spec.SetField(logicaldisk.FieldLabel, field.TypeString, value)
	}
	if value, ok := lduo.mutation.Filesystem(); ok {
		_spec.SetField(logicaldisk.FieldFilesystem, field.TypeString, value)
	}
	if lduo.mutation.FilesystemCleared() {
		_spec.ClearField(logicaldisk.FieldFilesystem, field.TypeString)
	}
	if value, ok := lduo.mutation.Usage(); ok {
		_spec.SetField(logicaldisk.FieldUsage, field.TypeInt8, value)
	}
	if value, ok := lduo.mutation.AddedUsage(); ok {
		_spec.AddField(logicaldisk.FieldUsage, field.TypeInt8, value)
	}
	if value, ok := lduo.mutation.SizeInUnits(); ok {
		_spec.SetField(logicaldisk.FieldSizeInUnits, field.TypeString, value)
	}
	if lduo.mutation.SizeInUnitsCleared() {
		_spec.ClearField(logicaldisk.FieldSizeInUnits, field.TypeString)
	}
	if value, ok := lduo.mutation.RemainingSpaceInUnits(); ok {
		_spec.SetField(logicaldisk.FieldRemainingSpaceInUnits, field.TypeString, value)
	}
	if lduo.mutation.RemainingSpaceInUnitsCleared() {
		_spec.ClearField(logicaldisk.FieldRemainingSpaceInUnits, field.TypeString)
	}
	if value, ok := lduo.mutation.VolumeName(); ok {
		_spec.SetField(logicaldisk.FieldVolumeName, field.TypeString, value)
	}
	if lduo.mutation.VolumeNameCleared() {
		_spec.ClearField(logicaldisk.FieldVolumeName, field.TypeString)
	}
	if value, ok := lduo.mutation.BitlockerStatus(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerStatus, field.TypeString, value)
	}
	if lduo.mutation.BitlockerStatusCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerStatus, field.TypeString)
	}
	if value, ok := lduo.mutation.VolumeType(); ok {
		_spec.SetField(logicaldisk.FieldVolumeType, field.TypeUint32, value)
	}
	if value, ok := lduo.mutation.AddedVolumeType(); ok {
		_spec.AddField(logicaldisk.FieldVolumeType, field.TypeUint32, value)
	}
	if lduo.mutation.VolumeTypeCleared() {
		_spec.ClearField(logicaldisk.FieldVolumeType, field.TypeUint32)
	}
	if value, ok := lduo.mutation.BitlockerConversionStatus(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerConversionStatus, field.TypeInt32, value)
	}
	if value, ok := lduo.mutation.AddedBitlockerConversionStatus(); ok {
		_spec.AddField(logicaldisk.FieldBitlockerConversionStatus, field.TypeInt32, value)
	}
	if lduo.mutation.BitlockerConversionStatusCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerConversionStatus, field.TypeInt32)
	}
	if value, ok := lduo.mutation.BitlockerEncryptionPercentage(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerEncryptionPercentage, field.TypeInt32, value)
	}
	if value, ok := lduo.mutation.AddedBitlockerEncryptionPercentage(); ok {
		_spec.AddField(logicaldisk.FieldBitlockerEncryptionPercentage, field.TypeInt32, value)
	}
	if lduo.mutation.BitlockerEncryptionPercentageCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerEncryptionPercentage, field.TypeInt32)
	}
	if value, ok := lduo.mutation.BitlockerRecoveryKey(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerRecoveryKey, field.TypeString, value)
	}
	if lduo.mutation.BitlockerRecoveryKeyCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerRecoveryKey, field.TypeString)
	}
	if value, ok := lduo.mutation.BitlockerOperationInProgress(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerOperationInProgress, field.TypeString, value)
	}
	if lduo.mutation.BitlockerOperationInProgressCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerOperationInProgress, field.TypeString)
	}
	if value, ok := lduo.mutation.BitlockerOperationResult(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerOperationResult, field.TypeString, value)
	}
	if lduo.mutation.BitlockerOperationResultCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerOperationResult, field.TypeString)
	}
	if value, ok := lduo.mutation.BitlockerIsAutoUnlockEnabled(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerIsAutoUnlockEnabled, field.TypeBool, value)
	}
	if lduo.mutation.BitlockerIsAutoUnlockEnabledCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerIsAutoUnlockEnabled, field.TypeBool)
	}
	if value, ok := lduo.mutation.BitlockerVolumeKeyProtectorID(); ok {
		_spec.SetField(logicaldisk.FieldBitlockerVolumeKeyProtectorID, field.TypeString, value)
	}
	if lduo.mutation.BitlockerVolumeKeyProtectorIDCleared() {
		_spec.ClearField(logicaldisk.FieldBitlockerVolumeKeyProtectorID, field.TypeString)
	}
	if lduo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logicaldisk.OwnerTable,
			Columns: []string{logicaldisk.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lduo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logicaldisk.OwnerTable,
			Columns: []string{logicaldisk.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(lduo.modifiers...)
	_node = &LogicalDisk{config: lduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logicaldisk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lduo.mutation.done = true
	return _node, nil
}
