// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/monitor"
)

// MonitorCreate is the builder for creating a Monitor entity.
type MonitorCreate struct {
	config
	mutation *MonitorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetManufacturer sets the "manufacturer" field.
func (_c *MonitorCreate) SetManufacturer(v string) *MonitorCreate {
	_c.mutation.SetManufacturer(v)
	return _c
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableManufacturer(v *string) *MonitorCreate {
	if v != nil {
		_c.SetManufacturer(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *MonitorCreate) SetModel(v string) *MonitorCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableModel(v *string) *MonitorCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSerial sets the "serial" field.
func (_c *MonitorCreate) SetSerial(v string) *MonitorCreate {
	_c.mutation.SetSerial(v)
	return _c
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableSerial(v *string) *MonitorCreate {
	if v != nil {
		_c.SetSerial(*v)
	}
	return _c
}

// SetWeekOfManufacture sets the "week_of_manufacture" field.
func (_c *MonitorCreate) SetWeekOfManufacture(v string) *MonitorCreate {
	_c.mutation.SetWeekOfManufacture(v)
	return _c
}

// SetNillableWeekOfManufacture sets the "week_of_manufacture" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableWeekOfManufacture(v *string) *MonitorCreate {
	if v != nil {
		_c.SetWeekOfManufacture(*v)
	}
	return _c
}

// SetYearOfManufacture sets the "year_of_manufacture" field.
func (_c *MonitorCreate) SetYearOfManufacture(v string) *MonitorCreate {
	_c.mutation.SetYearOfManufacture(v)
	return _c
}

// SetNillableYearOfManufacture sets the "year_of_manufacture" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableYearOfManufacture(v *string) *MonitorCreate {
	if v != nil {
		_c.SetYearOfManufacture(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the Agent entity by ID.
func (_c *MonitorCreate) SetOwnerID(id string) *MonitorCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the Agent entity.
func (_c *MonitorCreate) SetOwner(v *Agent) *MonitorCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the MonitorMutation object of the builder.
func (_c *MonitorCreate) Mutation() *MonitorMutation {
	return _c.mutation
}

// Save creates the Monitor in the database.
func (_c *MonitorCreate) Save(ctx context.Context) (*Monitor, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MonitorCreate) SaveX(ctx context.Context) *Monitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MonitorCreate) check() error {
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Monitor.owner"`)}
	}
	return nil
}

func (_c *MonitorCreate) sqlSave(ctx context.Context) (*Monitor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MonitorCreate) createSpec() (*Monitor, *sqlgraph.CreateSpec) {
	var (
		_node = &Monitor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(monitor.Table, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Manufacturer(); ok {
		_spec.SetField(monitor.FieldManufacturer, field.TypeString, value)
		_node.Manufacturer = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(monitor.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Serial(); ok {
		_spec.SetField(monitor.FieldSerial, field.TypeString, value)
		_node.Serial = value
	}
	if value, ok := _c.mutation.WeekOfManufacture(); ok {
		_spec.SetField(monitor.FieldWeekOfManufacture, field.TypeString, value)
		_node.WeekOfManufacture = value
	}
	if value, ok := _c.mutation.YearOfManufacture(); ok {
		_spec.SetField(monitor.FieldYearOfManufacture, field.TypeString, value)
		_node.YearOfManufacture = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   monitor.OwnerTable,
			Columns: []string{monitor.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.agent_monitors = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Monitor.Create().
//		SetManufacturer(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MonitorUpsert) {
//			SetManufacturer(v+v).
//		}).
//		Exec(ctx)
func (_c *MonitorCreate) OnConflict(opts ...sql.ConflictOption) *MonitorUpsertOne {
	_c.conflict = opts
	return &MonitorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MonitorCreate) OnConflictColumns(columns ...string) *MonitorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MonitorUpsertOne{
		create: _c,
	}
}

type (
	// MonitorUpsertOne is the builder for "upsert"-ing
	//  one Monitor node.
	MonitorUpsertOne struct {
		create *MonitorCreate
	}

	// MonitorUpsert is the "OnConflict" setter.
	MonitorUpsert struct {
		*sql.UpdateSet
	}
)

// SetManufacturer sets the "manufacturer" field.
func (u *MonitorUpsert) SetManufacturer(v string) *MonitorUpsert {
	u.Set(monitor.FieldManufacturer, v)
	return u
}

// UpdateManufacturer sets the "manufacturer" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateManufacturer() *MonitorUpsert {
	u.SetExcluded(monitor.FieldManufacturer)
	return u
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (u *MonitorUpsert) ClearManufacturer() *MonitorUpsert {
	u.SetNull(monitor.FieldManufacturer)
	return u
}

// SetModel sets the "model" field.
func (u *MonitorUpsert) SetModel(v string) *MonitorUpsert {
	u.Set(monitor.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateModel() *MonitorUpsert {
	u.SetExcluded(monitor.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *MonitorUpsert) ClearModel() *MonitorUpsert {
	u.SetNull(monitor.FieldModel)
	return u
}

// SetSerial sets the "serial" field.
func (u *MonitorUpsert) SetSerial(v string) *MonitorUpsert {
	u.Set(monitor.FieldSerial, v)
	return u
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateSerial() *MonitorUpsert {
	u.SetExcluded(monitor.FieldSerial)
	return u
}

// ClearSerial clears the value of the "serial" field.
func (u *MonitorUpsert) ClearSerial() *MonitorUpsert {
	u.SetNull(monitor.FieldSerial)
	return u
}

// SetWeekOfManufacture sets the "week_of_manufacture" field.
func (u *MonitorUpsert) SetWeekOfManufacture(v string) *MonitorUpsert {
	u.Set(monitor.FieldWeekOfManufacture, v)
	return u
}

// UpdateWeekOfManufacture sets the "week_of_manufacture" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateWeekOfManufacture() *MonitorUpsert {
	u.SetExcluded(monitor.FieldWeekOfManufacture)
	return u
}

// ClearWeekOfManufacture clears the value of the "week_of_manufacture" field.
func (u *MonitorUpsert) ClearWeekOfManufacture() *MonitorUpsert {
	u.SetNull(monitor.FieldWeekOfManufacture)
	return u
}

// SetYearOfManufacture sets the "year_of_manufacture" field.
func (u *MonitorUpsert) SetYearOfManufacture(v string) *MonitorUpsert {
	u.Set(monitor.FieldYearOfManufacture, v)
	return u
}

// UpdateYearOfManufacture sets the "year_of_manufacture" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateYearOfManufacture() *MonitorUpsert {
	u.SetExcluded(monitor.FieldYearOfManufacture)
	return u
}

// ClearYearOfManufacture clears the value of the "year_of_manufacture" field.
func (u *MonitorUpsert) ClearYearOfManufacture() *MonitorUpsert {
	u.SetNull(monitor.FieldYearOfManufacture)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MonitorUpsertOne) UpdateNewValues() *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Monitor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MonitorUpsertOne) Ignore() *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MonitorUpsertOne) DoNothing() *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MonitorCreate.OnConflict
// documentation for more info.
func (u *MonitorUpsertOne) Update(set func(*MonitorUpsert)) *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetManufacturer sets the "manufacturer" field.
func (u *MonitorUpsertOne) SetManufacturer(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetManufacturer(v)
	})
}

// UpdateManufacturer sets the "manufacturer" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateManufacturer() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateManufacturer()
	})
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (u *MonitorUpsertOne) ClearManufacturer() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearManufacturer()
	})
}

// SetModel sets the "model" field.
func (u *MonitorUpsertOne) SetModel(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateModel() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *MonitorUpsertOne) ClearModel() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearModel()
	})
}

// SetSerial sets the "serial" field.
func (u *MonitorUpsertOne) SetSerial(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateSerial() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateSerial()
	})
}

// ClearSerial clears the value of the "serial" field.
func (u *MonitorUpsertOne) ClearSerial() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearSerial()
	})
}

// SetWeekOfManufacture sets the "week_of_manufacture" field.
func (u *MonitorUpsertOne) SetWeekOfManufacture(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetWeekOfManufacture(v)
	})
}

// UpdateWeekOfManufacture sets the "week_of_manufacture" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateWeekOfManufacture() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateWeekOfManufacture()
	})
}

// ClearWeekOfManufacture clears the value of the "week_of_manufacture" field.
func (u *MonitorUpsertOne) ClearWeekOfManufacture() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearWeekOfManufacture()
	})
}

// SetYearOfManufacture sets the "year_of_manufacture" field.
func (u *MonitorUpsertOne) SetYearOfManufacture(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetYearOfManufacture(v)
	})
}

// UpdateYearOfManufacture sets the "year_of_manufacture" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateYearOfManufacture() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateYearOfManufacture()
	})
}

// ClearYearOfManufacture clears the value of the "year_of_manufacture" field.
func (u *MonitorUpsertOne) ClearYearOfManufacture() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearYearOfManufacture()
	})
}

// Exec executes the query.
func (u *MonitorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MonitorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MonitorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MonitorUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MonitorUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MonitorCreateBulk is the builder for creating many Monitor entities in bulk.
type MonitorCreateBulk struct {
	config
	err      error
	builders []*MonitorCreate
	conflict []sql.ConflictOption
}

// Save creates the Monitor entities in the database.
func (_c *MonitorCreateBulk) Save(ctx context.Context) ([]*Monitor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Monitor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MonitorCreateBulk) SaveX(ctx context.Context) []*Monitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Monitor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MonitorUpsert) {
//			SetManufacturer(v+v).
//		}).
//		Exec(ctx)
func (_c *MonitorCreateBulk) OnConflict(opts ...sql.ConflictOption) *MonitorUpsertBulk {
	_c.conflict = opts
	return &MonitorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MonitorCreateBulk) OnConflictColumns(columns ...string) *MonitorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MonitorUpsertBulk{
		create: _c,
	}
}

// MonitorUpsertBulk is the builder for "upsert"-ing
// a bulk of Monitor nodes.
type MonitorUpsertBulk struct {
	create *MonitorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MonitorUpsertBulk) UpdateNewValues() *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MonitorUpsertBulk) Ignore() *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MonitorUpsertBulk) DoNothing() *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MonitorCreateBulk.OnConflict
// documentation for more info.
func (u *MonitorUpsertBulk) Update(set func(*MonitorUpsert)) *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetManufacturer sets the "manufacturer" field.
func (u *MonitorUpsertBulk) SetManufacturer(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetManufacturer(v)
	})
}

// UpdateManufacturer sets the "manufacturer" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateManufacturer() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateManufacturer()
	})
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (u *MonitorUpsertBulk) ClearManufacturer() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearManufacturer()
	})
}

// SetModel sets the "model" field.
func (u *MonitorUpsertBulk) SetModel(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateModel() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *MonitorUpsertBulk) ClearModel() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearModel()
	})
}

// SetSerial sets the "serial" field.
func (u *MonitorUpsertBulk) SetSerial(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateSerial() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateSerial()
	})
}

// ClearSerial clears the value of the "serial" field.
func (u *MonitorUpsertBulk) ClearSerial() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearSerial()
	})
}

// SetWeekOfManufacture sets the "week_of_manufacture" field.
func (u *MonitorUpsertBulk) SetWeekOfManufacture(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetWeekOfManufacture(v)
	})
}

// UpdateWeekOfManufacture sets the "week_of_manufacture" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateWeekOfManufacture() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateWeekOfManufacture()
	})
}

// ClearWeekOfManufacture clears the value of the "week_of_manufacture" field.
func (u *MonitorUpsertBulk) ClearWeekOfManufacture() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearWeekOfManufacture()
	})
}

// SetYearOfManufacture sets the "year_of_manufacture" field.
func (u *MonitorUpsertBulk) SetYearOfManufacture(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetYearOfManufacture(v)
	})
}

// UpdateYearOfManufacture sets the "year_of_manufacture" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateYearOfManufacture() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateYearOfManufacture()
	})
}

// ClearYearOfManufacture clears the value of the "year_of_manufacture" field.
func (u *MonitorUpsertBulk) ClearYearOfManufacture() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearYearOfManufacture()
	})
}

// Exec executes the query.
func (u *MonitorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MonitorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MonitorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MonitorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
