// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/nanomdmuser"
	"github.com/open-uem/ent/predicate"
)

// NanoMDMUserQuery is the builder for querying NanoMDMUser entities.
type NanoMDMUserQuery struct {
	config
	ctx        *QueryContext
	order      []nanomdmuser.OrderOption
	inters     []Interceptor
	predicates []predicate.NanoMDMUser
	withAgent  *AgentQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NanoMDMUserQuery builder.
func (nmuq *NanoMDMUserQuery) Where(ps ...predicate.NanoMDMUser) *NanoMDMUserQuery {
	nmuq.predicates = append(nmuq.predicates, ps...)
	return nmuq
}

// Limit the number of records to be returned by this query.
func (nmuq *NanoMDMUserQuery) Limit(limit int) *NanoMDMUserQuery {
	nmuq.ctx.Limit = &limit
	return nmuq
}

// Offset to start from.
func (nmuq *NanoMDMUserQuery) Offset(offset int) *NanoMDMUserQuery {
	nmuq.ctx.Offset = &offset
	return nmuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nmuq *NanoMDMUserQuery) Unique(unique bool) *NanoMDMUserQuery {
	nmuq.ctx.Unique = &unique
	return nmuq
}

// Order specifies how the records should be ordered.
func (nmuq *NanoMDMUserQuery) Order(o ...nanomdmuser.OrderOption) *NanoMDMUserQuery {
	nmuq.order = append(nmuq.order, o...)
	return nmuq
}

// QueryAgent chains the current query on the "agent" edge.
func (nmuq *NanoMDMUserQuery) QueryAgent() *AgentQuery {
	query := (&AgentClient{config: nmuq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nmuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nmuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nanomdmuser.Table, nanomdmuser.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, nanomdmuser.AgentTable, nanomdmuser.AgentColumn),
		)
		fromU = sqlgraph.SetNeighbors(nmuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NanoMDMUser entity from the query.
// Returns a *NotFoundError when no NanoMDMUser was found.
func (nmuq *NanoMDMUserQuery) First(ctx context.Context) (*NanoMDMUser, error) {
	nodes, err := nmuq.Limit(1).All(setContextOp(ctx, nmuq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nanomdmuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) FirstX(ctx context.Context) *NanoMDMUser {
	node, err := nmuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NanoMDMUser ID from the query.
// Returns a *NotFoundError when no NanoMDMUser ID was found.
func (nmuq *NanoMDMUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nmuq.Limit(1).IDs(setContextOp(ctx, nmuq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nanomdmuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) FirstIDX(ctx context.Context) int {
	id, err := nmuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NanoMDMUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NanoMDMUser entity is found.
// Returns a *NotFoundError when no NanoMDMUser entities are found.
func (nmuq *NanoMDMUserQuery) Only(ctx context.Context) (*NanoMDMUser, error) {
	nodes, err := nmuq.Limit(2).All(setContextOp(ctx, nmuq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nanomdmuser.Label}
	default:
		return nil, &NotSingularError{nanomdmuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) OnlyX(ctx context.Context) *NanoMDMUser {
	node, err := nmuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NanoMDMUser ID in the query.
// Returns a *NotSingularError when more than one NanoMDMUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (nmuq *NanoMDMUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nmuq.Limit(2).IDs(setContextOp(ctx, nmuq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nanomdmuser.Label}
	default:
		err = &NotSingularError{nanomdmuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := nmuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NanoMDMUsers.
func (nmuq *NanoMDMUserQuery) All(ctx context.Context) ([]*NanoMDMUser, error) {
	ctx = setContextOp(ctx, nmuq.ctx, ent.OpQueryAll)
	if err := nmuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NanoMDMUser, *NanoMDMUserQuery]()
	return withInterceptors[[]*NanoMDMUser](ctx, nmuq, qr, nmuq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) AllX(ctx context.Context) []*NanoMDMUser {
	nodes, err := nmuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NanoMDMUser IDs.
func (nmuq *NanoMDMUserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if nmuq.ctx.Unique == nil && nmuq.path != nil {
		nmuq.Unique(true)
	}
	ctx = setContextOp(ctx, nmuq.ctx, ent.OpQueryIDs)
	if err = nmuq.Select(nanomdmuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) IDsX(ctx context.Context) []int {
	ids, err := nmuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nmuq *NanoMDMUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nmuq.ctx, ent.OpQueryCount)
	if err := nmuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nmuq, querierCount[*NanoMDMUserQuery](), nmuq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) CountX(ctx context.Context) int {
	count, err := nmuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nmuq *NanoMDMUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nmuq.ctx, ent.OpQueryExist)
	switch _, err := nmuq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nmuq *NanoMDMUserQuery) ExistX(ctx context.Context) bool {
	exist, err := nmuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NanoMDMUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nmuq *NanoMDMUserQuery) Clone() *NanoMDMUserQuery {
	if nmuq == nil {
		return nil
	}
	return &NanoMDMUserQuery{
		config:     nmuq.config,
		ctx:        nmuq.ctx.Clone(),
		order:      append([]nanomdmuser.OrderOption{}, nmuq.order...),
		inters:     append([]Interceptor{}, nmuq.inters...),
		predicates: append([]predicate.NanoMDMUser{}, nmuq.predicates...),
		withAgent:  nmuq.withAgent.Clone(),
		// clone intermediate query.
		sql:       nmuq.sql.Clone(),
		path:      nmuq.path,
		modifiers: append([]func(*sql.Selector){}, nmuq.modifiers...),
	}
}

// WithAgent tells the query-builder to eager-load the nodes that are connected to
// the "agent" edge. The optional arguments are used to configure the query builder of the edge.
func (nmuq *NanoMDMUserQuery) WithAgent(opts ...func(*AgentQuery)) *NanoMDMUserQuery {
	query := (&AgentClient{config: nmuq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nmuq.withAgent = query
	return nmuq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DataQuota int `json:"data_quota,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NanoMDMUser.Query().
//		GroupBy(nanomdmuser.FieldDataQuota).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nmuq *NanoMDMUserQuery) GroupBy(field string, fields ...string) *NanoMDMUserGroupBy {
	nmuq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NanoMDMUserGroupBy{build: nmuq}
	grbuild.flds = &nmuq.ctx.Fields
	grbuild.label = nanomdmuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DataQuota int `json:"data_quota,omitempty"`
//	}
//
//	client.NanoMDMUser.Query().
//		Select(nanomdmuser.FieldDataQuota).
//		Scan(ctx, &v)
func (nmuq *NanoMDMUserQuery) Select(fields ...string) *NanoMDMUserSelect {
	nmuq.ctx.Fields = append(nmuq.ctx.Fields, fields...)
	sbuild := &NanoMDMUserSelect{NanoMDMUserQuery: nmuq}
	sbuild.label = nanomdmuser.Label
	sbuild.flds, sbuild.scan = &nmuq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NanoMDMUserSelect configured with the given aggregations.
func (nmuq *NanoMDMUserQuery) Aggregate(fns ...AggregateFunc) *NanoMDMUserSelect {
	return nmuq.Select().Aggregate(fns...)
}

func (nmuq *NanoMDMUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nmuq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nmuq); err != nil {
				return err
			}
		}
	}
	for _, f := range nmuq.ctx.Fields {
		if !nanomdmuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nmuq.path != nil {
		prev, err := nmuq.path(ctx)
		if err != nil {
			return err
		}
		nmuq.sql = prev
	}
	return nil
}

func (nmuq *NanoMDMUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NanoMDMUser, error) {
	var (
		nodes       = []*NanoMDMUser{}
		withFKs     = nmuq.withFKs
		_spec       = nmuq.querySpec()
		loadedTypes = [1]bool{
			nmuq.withAgent != nil,
		}
	)
	if nmuq.withAgent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, nanomdmuser.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NanoMDMUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NanoMDMUser{config: nmuq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(nmuq.modifiers) > 0 {
		_spec.Modifiers = nmuq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nmuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nmuq.withAgent; query != nil {
		if err := nmuq.loadAgent(ctx, query, nodes, nil,
			func(n *NanoMDMUser, e *Agent) { n.Edges.Agent = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nmuq *NanoMDMUserQuery) loadAgent(ctx context.Context, query *AgentQuery, nodes []*NanoMDMUser, init func(*NanoMDMUser), assign func(*NanoMDMUser, *Agent)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*NanoMDMUser)
	for i := range nodes {
		if nodes[i].agent_nanomdmusers == nil {
			continue
		}
		fk := *nodes[i].agent_nanomdmusers
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_nanomdmusers" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (nmuq *NanoMDMUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nmuq.querySpec()
	if len(nmuq.modifiers) > 0 {
		_spec.Modifiers = nmuq.modifiers
	}
	_spec.Node.Columns = nmuq.ctx.Fields
	if len(nmuq.ctx.Fields) > 0 {
		_spec.Unique = nmuq.ctx.Unique != nil && *nmuq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nmuq.driver, _spec)
}

func (nmuq *NanoMDMUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nanomdmuser.Table, nanomdmuser.Columns, sqlgraph.NewFieldSpec(nanomdmuser.FieldID, field.TypeInt))
	_spec.From = nmuq.sql
	if unique := nmuq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nmuq.path != nil {
		_spec.Unique = true
	}
	if fields := nmuq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nanomdmuser.FieldID)
		for i := range fields {
			if fields[i] != nanomdmuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nmuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nmuq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nmuq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nmuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nmuq *NanoMDMUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nmuq.driver.Dialect())
	t1 := builder.Table(nanomdmuser.Table)
	columns := nmuq.ctx.Fields
	if len(columns) == 0 {
		columns = nanomdmuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nmuq.sql != nil {
		selector = nmuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nmuq.ctx.Unique != nil && *nmuq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range nmuq.modifiers {
		m(selector)
	}
	for _, p := range nmuq.predicates {
		p(selector)
	}
	for _, p := range nmuq.order {
		p(selector)
	}
	if offset := nmuq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nmuq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nmuq *NanoMDMUserQuery) Modify(modifiers ...func(s *sql.Selector)) *NanoMDMUserSelect {
	nmuq.modifiers = append(nmuq.modifiers, modifiers...)
	return nmuq.Select()
}

// NanoMDMUserGroupBy is the group-by builder for NanoMDMUser entities.
type NanoMDMUserGroupBy struct {
	selector
	build *NanoMDMUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nmugb *NanoMDMUserGroupBy) Aggregate(fns ...AggregateFunc) *NanoMDMUserGroupBy {
	nmugb.fns = append(nmugb.fns, fns...)
	return nmugb
}

// Scan applies the selector query and scans the result into the given value.
func (nmugb *NanoMDMUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nmugb.build.ctx, ent.OpQueryGroupBy)
	if err := nmugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NanoMDMUserQuery, *NanoMDMUserGroupBy](ctx, nmugb.build, nmugb, nmugb.build.inters, v)
}

func (nmugb *NanoMDMUserGroupBy) sqlScan(ctx context.Context, root *NanoMDMUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nmugb.fns))
	for _, fn := range nmugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nmugb.flds)+len(nmugb.fns))
		for _, f := range *nmugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nmugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nmugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NanoMDMUserSelect is the builder for selecting fields of NanoMDMUser entities.
type NanoMDMUserSelect struct {
	*NanoMDMUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nmus *NanoMDMUserSelect) Aggregate(fns ...AggregateFunc) *NanoMDMUserSelect {
	nmus.fns = append(nmus.fns, fns...)
	return nmus
}

// Scan applies the selector query and scans the result into the given value.
func (nmus *NanoMDMUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nmus.ctx, ent.OpQuerySelect)
	if err := nmus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NanoMDMUserQuery, *NanoMDMUserSelect](ctx, nmus.NanoMDMUserQuery, nmus, nmus.inters, v)
}

func (nmus *NanoMDMUserSelect) sqlScan(ctx context.Context, root *NanoMDMUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nmus.fns))
	for _, fn := range nmus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nmus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nmus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nmus *NanoMDMUserSelect) Modify(modifiers ...func(s *sql.Selector)) *NanoMDMUserSelect {
	nmus.modifiers = append(nmus.modifiers, modifiers...)
	return nmus
}
