// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/netbird"
)

// NetbirdCreate is the builder for creating a Netbird entity.
type NetbirdCreate struct {
	config
	mutation *NetbirdMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVersion sets the "version" field.
func (nc *NetbirdCreate) SetVersion(s string) *NetbirdCreate {
	nc.mutation.SetVersion(s)
	return nc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableVersion(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetVersion(*s)
	}
	return nc
}

// SetInstalled sets the "installed" field.
func (nc *NetbirdCreate) SetInstalled(b bool) *NetbirdCreate {
	nc.mutation.SetInstalled(b)
	return nc
}

// SetNillableInstalled sets the "installed" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableInstalled(b *bool) *NetbirdCreate {
	if b != nil {
		nc.SetInstalled(*b)
	}
	return nc
}

// SetServiceStatus sets the "service_status" field.
func (nc *NetbirdCreate) SetServiceStatus(s string) *NetbirdCreate {
	nc.mutation.SetServiceStatus(s)
	return nc
}

// SetNillableServiceStatus sets the "service_status" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableServiceStatus(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetServiceStatus(*s)
	}
	return nc
}

// SetIP sets the "ip" field.
func (nc *NetbirdCreate) SetIP(s string) *NetbirdCreate {
	nc.mutation.SetIP(s)
	return nc
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableIP(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetIP(*s)
	}
	return nc
}

// SetProfile sets the "profile" field.
func (nc *NetbirdCreate) SetProfile(s string) *NetbirdCreate {
	nc.mutation.SetProfile(s)
	return nc
}

// SetNillableProfile sets the "profile" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableProfile(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetProfile(*s)
	}
	return nc
}

// SetManagementURL sets the "management_url" field.
func (nc *NetbirdCreate) SetManagementURL(s string) *NetbirdCreate {
	nc.mutation.SetManagementURL(s)
	return nc
}

// SetNillableManagementURL sets the "management_url" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableManagementURL(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetManagementURL(*s)
	}
	return nc
}

// SetManagementConnected sets the "management_connected" field.
func (nc *NetbirdCreate) SetManagementConnected(b bool) *NetbirdCreate {
	nc.mutation.SetManagementConnected(b)
	return nc
}

// SetNillableManagementConnected sets the "management_connected" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableManagementConnected(b *bool) *NetbirdCreate {
	if b != nil {
		nc.SetManagementConnected(*b)
	}
	return nc
}

// SetSignalURL sets the "signal_url" field.
func (nc *NetbirdCreate) SetSignalURL(s string) *NetbirdCreate {
	nc.mutation.SetSignalURL(s)
	return nc
}

// SetNillableSignalURL sets the "signal_url" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableSignalURL(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetSignalURL(*s)
	}
	return nc
}

// SetSignalConnected sets the "signal_connected" field.
func (nc *NetbirdCreate) SetSignalConnected(b bool) *NetbirdCreate {
	nc.mutation.SetSignalConnected(b)
	return nc
}

// SetNillableSignalConnected sets the "signal_connected" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableSignalConnected(b *bool) *NetbirdCreate {
	if b != nil {
		nc.SetSignalConnected(*b)
	}
	return nc
}

// SetSSHEnabled sets the "ssh_enabled" field.
func (nc *NetbirdCreate) SetSSHEnabled(b bool) *NetbirdCreate {
	nc.mutation.SetSSHEnabled(b)
	return nc
}

// SetNillableSSHEnabled sets the "ssh_enabled" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableSSHEnabled(b *bool) *NetbirdCreate {
	if b != nil {
		nc.SetSSHEnabled(*b)
	}
	return nc
}

// SetPeersTotal sets the "peers_total" field.
func (nc *NetbirdCreate) SetPeersTotal(i int) *NetbirdCreate {
	nc.mutation.SetPeersTotal(i)
	return nc
}

// SetNillablePeersTotal sets the "peers_total" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillablePeersTotal(i *int) *NetbirdCreate {
	if i != nil {
		nc.SetPeersTotal(*i)
	}
	return nc
}

// SetPeersConnected sets the "peers_connected" field.
func (nc *NetbirdCreate) SetPeersConnected(i int) *NetbirdCreate {
	nc.mutation.SetPeersConnected(i)
	return nc
}

// SetNillablePeersConnected sets the "peers_connected" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillablePeersConnected(i *int) *NetbirdCreate {
	if i != nil {
		nc.SetPeersConnected(*i)
	}
	return nc
}

// SetProfilesAvailable sets the "profiles_available" field.
func (nc *NetbirdCreate) SetProfilesAvailable(s string) *NetbirdCreate {
	nc.mutation.SetProfilesAvailable(s)
	return nc
}

// SetNillableProfilesAvailable sets the "profiles_available" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableProfilesAvailable(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetProfilesAvailable(*s)
	}
	return nc
}

// SetDNSServer sets the "dns_server" field.
func (nc *NetbirdCreate) SetDNSServer(s string) *NetbirdCreate {
	nc.mutation.SetDNSServer(s)
	return nc
}

// SetNillableDNSServer sets the "dns_server" field if the given value is not nil.
func (nc *NetbirdCreate) SetNillableDNSServer(s *string) *NetbirdCreate {
	if s != nil {
		nc.SetDNSServer(*s)
	}
	return nc
}

// SetOwnerID sets the "owner" edge to the Agent entity by ID.
func (nc *NetbirdCreate) SetOwnerID(id string) *NetbirdCreate {
	nc.mutation.SetOwnerID(id)
	return nc
}

// SetOwner sets the "owner" edge to the Agent entity.
func (nc *NetbirdCreate) SetOwner(a *Agent) *NetbirdCreate {
	return nc.SetOwnerID(a.ID)
}

// Mutation returns the NetbirdMutation object of the builder.
func (nc *NetbirdCreate) Mutation() *NetbirdMutation {
	return nc.mutation
}

// Save creates the Netbird in the database.
func (nc *NetbirdCreate) Save(ctx context.Context) (*Netbird, error) {
	nc.defaults()
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NetbirdCreate) SaveX(ctx context.Context) *Netbird {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NetbirdCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NetbirdCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nc *NetbirdCreate) defaults() {
	if _, ok := nc.mutation.Version(); !ok {
		v := netbird.DefaultVersion
		nc.mutation.SetVersion(v)
	}
	if _, ok := nc.mutation.Installed(); !ok {
		v := netbird.DefaultInstalled
		nc.mutation.SetInstalled(v)
	}
	if _, ok := nc.mutation.ServiceStatus(); !ok {
		v := netbird.DefaultServiceStatus
		nc.mutation.SetServiceStatus(v)
	}
	if _, ok := nc.mutation.IP(); !ok {
		v := netbird.DefaultIP
		nc.mutation.SetIP(v)
	}
	if _, ok := nc.mutation.Profile(); !ok {
		v := netbird.DefaultProfile
		nc.mutation.SetProfile(v)
	}
	if _, ok := nc.mutation.ManagementURL(); !ok {
		v := netbird.DefaultManagementURL
		nc.mutation.SetManagementURL(v)
	}
	if _, ok := nc.mutation.ManagementConnected(); !ok {
		v := netbird.DefaultManagementConnected
		nc.mutation.SetManagementConnected(v)
	}
	if _, ok := nc.mutation.SignalURL(); !ok {
		v := netbird.DefaultSignalURL
		nc.mutation.SetSignalURL(v)
	}
	if _, ok := nc.mutation.SignalConnected(); !ok {
		v := netbird.DefaultSignalConnected
		nc.mutation.SetSignalConnected(v)
	}
	if _, ok := nc.mutation.SSHEnabled(); !ok {
		v := netbird.DefaultSSHEnabled
		nc.mutation.SetSSHEnabled(v)
	}
	if _, ok := nc.mutation.PeersTotal(); !ok {
		v := netbird.DefaultPeersTotal
		nc.mutation.SetPeersTotal(v)
	}
	if _, ok := nc.mutation.PeersConnected(); !ok {
		v := netbird.DefaultPeersConnected
		nc.mutation.SetPeersConnected(v)
	}
	if _, ok := nc.mutation.ProfilesAvailable(); !ok {
		v := netbird.DefaultProfilesAvailable
		nc.mutation.SetProfilesAvailable(v)
	}
	if _, ok := nc.mutation.DNSServer(); !ok {
		v := netbird.DefaultDNSServer
		nc.mutation.SetDNSServer(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NetbirdCreate) check() error {
	if _, ok := nc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Netbird.version"`)}
	}
	if _, ok := nc.mutation.Installed(); !ok {
		return &ValidationError{Name: "installed", err: errors.New(`ent: missing required field "Netbird.installed"`)}
	}
	if _, ok := nc.mutation.ServiceStatus(); !ok {
		return &ValidationError{Name: "service_status", err: errors.New(`ent: missing required field "Netbird.service_status"`)}
	}
	if _, ok := nc.mutation.ManagementConnected(); !ok {
		return &ValidationError{Name: "management_connected", err: errors.New(`ent: missing required field "Netbird.management_connected"`)}
	}
	if _, ok := nc.mutation.SignalConnected(); !ok {
		return &ValidationError{Name: "signal_connected", err: errors.New(`ent: missing required field "Netbird.signal_connected"`)}
	}
	if _, ok := nc.mutation.SSHEnabled(); !ok {
		return &ValidationError{Name: "ssh_enabled", err: errors.New(`ent: missing required field "Netbird.ssh_enabled"`)}
	}
	if len(nc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Netbird.owner"`)}
	}
	return nil
}

func (nc *NetbirdCreate) sqlSave(ctx context.Context) (*Netbird, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NetbirdCreate) createSpec() (*Netbird, *sqlgraph.CreateSpec) {
	var (
		_node = &Netbird{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(netbird.Table, sqlgraph.NewFieldSpec(netbird.FieldID, field.TypeInt))
	)
	_spec.OnConflict = nc.conflict
	if value, ok := nc.mutation.Version(); ok {
		_spec.SetField(netbird.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := nc.mutation.Installed(); ok {
		_spec.SetField(netbird.FieldInstalled, field.TypeBool, value)
		_node.Installed = value
	}
	if value, ok := nc.mutation.ServiceStatus(); ok {
		_spec.SetField(netbird.FieldServiceStatus, field.TypeString, value)
		_node.ServiceStatus = value
	}
	if value, ok := nc.mutation.IP(); ok {
		_spec.SetField(netbird.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := nc.mutation.Profile(); ok {
		_spec.SetField(netbird.FieldProfile, field.TypeString, value)
		_node.Profile = value
	}
	if value, ok := nc.mutation.ManagementURL(); ok {
		_spec.SetField(netbird.FieldManagementURL, field.TypeString, value)
		_node.ManagementURL = value
	}
	if value, ok := nc.mutation.ManagementConnected(); ok {
		_spec.SetField(netbird.FieldManagementConnected, field.TypeBool, value)
		_node.ManagementConnected = value
	}
	if value, ok := nc.mutation.SignalURL(); ok {
		_spec.SetField(netbird.FieldSignalURL, field.TypeString, value)
		_node.SignalURL = value
	}
	if value, ok := nc.mutation.SignalConnected(); ok {
		_spec.SetField(netbird.FieldSignalConnected, field.TypeBool, value)
		_node.SignalConnected = value
	}
	if value, ok := nc.mutation.SSHEnabled(); ok {
		_spec.SetField(netbird.FieldSSHEnabled, field.TypeBool, value)
		_node.SSHEnabled = value
	}
	if value, ok := nc.mutation.PeersTotal(); ok {
		_spec.SetField(netbird.FieldPeersTotal, field.TypeInt, value)
		_node.PeersTotal = value
	}
	if value, ok := nc.mutation.PeersConnected(); ok {
		_spec.SetField(netbird.FieldPeersConnected, field.TypeInt, value)
		_node.PeersConnected = value
	}
	if value, ok := nc.mutation.ProfilesAvailable(); ok {
		_spec.SetField(netbird.FieldProfilesAvailable, field.TypeString, value)
		_node.ProfilesAvailable = value
	}
	if value, ok := nc.mutation.DNSServer(); ok {
		_spec.SetField(netbird.FieldDNSServer, field.TypeString, value)
		_node.DNSServer = value
	}
	if nodes := nc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   netbird.OwnerTable,
			Columns: []string{netbird.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.agent_netbird = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Netbird.Create().
//		SetVersion(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NetbirdUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (nc *NetbirdCreate) OnConflict(opts ...sql.ConflictOption) *NetbirdUpsertOne {
	nc.conflict = opts
	return &NetbirdUpsertOne{
		create: nc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Netbird.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nc *NetbirdCreate) OnConflictColumns(columns ...string) *NetbirdUpsertOne {
	nc.conflict = append(nc.conflict, sql.ConflictColumns(columns...))
	return &NetbirdUpsertOne{
		create: nc,
	}
}

type (
	// NetbirdUpsertOne is the builder for "upsert"-ing
	//  one Netbird node.
	NetbirdUpsertOne struct {
		create *NetbirdCreate
	}

	// NetbirdUpsert is the "OnConflict" setter.
	NetbirdUpsert struct {
		*sql.UpdateSet
	}
)

// SetVersion sets the "version" field.
func (u *NetbirdUpsert) SetVersion(v string) *NetbirdUpsert {
	u.Set(netbird.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateVersion() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldVersion)
	return u
}

// SetInstalled sets the "installed" field.
func (u *NetbirdUpsert) SetInstalled(v bool) *NetbirdUpsert {
	u.Set(netbird.FieldInstalled, v)
	return u
}

// UpdateInstalled sets the "installed" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateInstalled() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldInstalled)
	return u
}

// SetServiceStatus sets the "service_status" field.
func (u *NetbirdUpsert) SetServiceStatus(v string) *NetbirdUpsert {
	u.Set(netbird.FieldServiceStatus, v)
	return u
}

// UpdateServiceStatus sets the "service_status" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateServiceStatus() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldServiceStatus)
	return u
}

// SetIP sets the "ip" field.
func (u *NetbirdUpsert) SetIP(v string) *NetbirdUpsert {
	u.Set(netbird.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateIP() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *NetbirdUpsert) ClearIP() *NetbirdUpsert {
	u.SetNull(netbird.FieldIP)
	return u
}

// SetProfile sets the "profile" field.
func (u *NetbirdUpsert) SetProfile(v string) *NetbirdUpsert {
	u.Set(netbird.FieldProfile, v)
	return u
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateProfile() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldProfile)
	return u
}

// ClearProfile clears the value of the "profile" field.
func (u *NetbirdUpsert) ClearProfile() *NetbirdUpsert {
	u.SetNull(netbird.FieldProfile)
	return u
}

// SetManagementURL sets the "management_url" field.
func (u *NetbirdUpsert) SetManagementURL(v string) *NetbirdUpsert {
	u.Set(netbird.FieldManagementURL, v)
	return u
}

// UpdateManagementURL sets the "management_url" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateManagementURL() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldManagementURL)
	return u
}

// ClearManagementURL clears the value of the "management_url" field.
func (u *NetbirdUpsert) ClearManagementURL() *NetbirdUpsert {
	u.SetNull(netbird.FieldManagementURL)
	return u
}

// SetManagementConnected sets the "management_connected" field.
func (u *NetbirdUpsert) SetManagementConnected(v bool) *NetbirdUpsert {
	u.Set(netbird.FieldManagementConnected, v)
	return u
}

// UpdateManagementConnected sets the "management_connected" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateManagementConnected() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldManagementConnected)
	return u
}

// SetSignalURL sets the "signal_url" field.
func (u *NetbirdUpsert) SetSignalURL(v string) *NetbirdUpsert {
	u.Set(netbird.FieldSignalURL, v)
	return u
}

// UpdateSignalURL sets the "signal_url" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateSignalURL() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldSignalURL)
	return u
}

// ClearSignalURL clears the value of the "signal_url" field.
func (u *NetbirdUpsert) ClearSignalURL() *NetbirdUpsert {
	u.SetNull(netbird.FieldSignalURL)
	return u
}

// SetSignalConnected sets the "signal_connected" field.
func (u *NetbirdUpsert) SetSignalConnected(v bool) *NetbirdUpsert {
	u.Set(netbird.FieldSignalConnected, v)
	return u
}

// UpdateSignalConnected sets the "signal_connected" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateSignalConnected() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldSignalConnected)
	return u
}

// SetSSHEnabled sets the "ssh_enabled" field.
func (u *NetbirdUpsert) SetSSHEnabled(v bool) *NetbirdUpsert {
	u.Set(netbird.FieldSSHEnabled, v)
	return u
}

// UpdateSSHEnabled sets the "ssh_enabled" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateSSHEnabled() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldSSHEnabled)
	return u
}

// SetPeersTotal sets the "peers_total" field.
func (u *NetbirdUpsert) SetPeersTotal(v int) *NetbirdUpsert {
	u.Set(netbird.FieldPeersTotal, v)
	return u
}

// UpdatePeersTotal sets the "peers_total" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdatePeersTotal() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldPeersTotal)
	return u
}

// AddPeersTotal adds v to the "peers_total" field.
func (u *NetbirdUpsert) AddPeersTotal(v int) *NetbirdUpsert {
	u.Add(netbird.FieldPeersTotal, v)
	return u
}

// ClearPeersTotal clears the value of the "peers_total" field.
func (u *NetbirdUpsert) ClearPeersTotal() *NetbirdUpsert {
	u.SetNull(netbird.FieldPeersTotal)
	return u
}

// SetPeersConnected sets the "peers_connected" field.
func (u *NetbirdUpsert) SetPeersConnected(v int) *NetbirdUpsert {
	u.Set(netbird.FieldPeersConnected, v)
	return u
}

// UpdatePeersConnected sets the "peers_connected" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdatePeersConnected() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldPeersConnected)
	return u
}

// AddPeersConnected adds v to the "peers_connected" field.
func (u *NetbirdUpsert) AddPeersConnected(v int) *NetbirdUpsert {
	u.Add(netbird.FieldPeersConnected, v)
	return u
}

// ClearPeersConnected clears the value of the "peers_connected" field.
func (u *NetbirdUpsert) ClearPeersConnected() *NetbirdUpsert {
	u.SetNull(netbird.FieldPeersConnected)
	return u
}

// SetProfilesAvailable sets the "profiles_available" field.
func (u *NetbirdUpsert) SetProfilesAvailable(v string) *NetbirdUpsert {
	u.Set(netbird.FieldProfilesAvailable, v)
	return u
}

// UpdateProfilesAvailable sets the "profiles_available" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateProfilesAvailable() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldProfilesAvailable)
	return u
}

// ClearProfilesAvailable clears the value of the "profiles_available" field.
func (u *NetbirdUpsert) ClearProfilesAvailable() *NetbirdUpsert {
	u.SetNull(netbird.FieldProfilesAvailable)
	return u
}

// SetDNSServer sets the "dns_server" field.
func (u *NetbirdUpsert) SetDNSServer(v string) *NetbirdUpsert {
	u.Set(netbird.FieldDNSServer, v)
	return u
}

// UpdateDNSServer sets the "dns_server" field to the value that was provided on create.
func (u *NetbirdUpsert) UpdateDNSServer() *NetbirdUpsert {
	u.SetExcluded(netbird.FieldDNSServer)
	return u
}

// ClearDNSServer clears the value of the "dns_server" field.
func (u *NetbirdUpsert) ClearDNSServer() *NetbirdUpsert {
	u.SetNull(netbird.FieldDNSServer)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Netbird.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NetbirdUpsertOne) UpdateNewValues() *NetbirdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Netbird.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NetbirdUpsertOne) Ignore() *NetbirdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NetbirdUpsertOne) DoNothing() *NetbirdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NetbirdCreate.OnConflict
// documentation for more info.
func (u *NetbirdUpsertOne) Update(set func(*NetbirdUpsert)) *NetbirdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NetbirdUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *NetbirdUpsertOne) SetVersion(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateVersion() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateVersion()
	})
}

// SetInstalled sets the "installed" field.
func (u *NetbirdUpsertOne) SetInstalled(v bool) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetInstalled(v)
	})
}

// UpdateInstalled sets the "installed" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateInstalled() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateInstalled()
	})
}

// SetServiceStatus sets the "service_status" field.
func (u *NetbirdUpsertOne) SetServiceStatus(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetServiceStatus(v)
	})
}

// UpdateServiceStatus sets the "service_status" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateServiceStatus() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateServiceStatus()
	})
}

// SetIP sets the "ip" field.
func (u *NetbirdUpsertOne) SetIP(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateIP() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *NetbirdUpsertOne) ClearIP() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearIP()
	})
}

// SetProfile sets the "profile" field.
func (u *NetbirdUpsertOne) SetProfile(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateProfile() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateProfile()
	})
}

// ClearProfile clears the value of the "profile" field.
func (u *NetbirdUpsertOne) ClearProfile() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearProfile()
	})
}

// SetManagementURL sets the "management_url" field.
func (u *NetbirdUpsertOne) SetManagementURL(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetManagementURL(v)
	})
}

// UpdateManagementURL sets the "management_url" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateManagementURL() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateManagementURL()
	})
}

// ClearManagementURL clears the value of the "management_url" field.
func (u *NetbirdUpsertOne) ClearManagementURL() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearManagementURL()
	})
}

// SetManagementConnected sets the "management_connected" field.
func (u *NetbirdUpsertOne) SetManagementConnected(v bool) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetManagementConnected(v)
	})
}

// UpdateManagementConnected sets the "management_connected" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateManagementConnected() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateManagementConnected()
	})
}

// SetSignalURL sets the "signal_url" field.
func (u *NetbirdUpsertOne) SetSignalURL(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetSignalURL(v)
	})
}

// UpdateSignalURL sets the "signal_url" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateSignalURL() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateSignalURL()
	})
}

// ClearSignalURL clears the value of the "signal_url" field.
func (u *NetbirdUpsertOne) ClearSignalURL() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearSignalURL()
	})
}

// SetSignalConnected sets the "signal_connected" field.
func (u *NetbirdUpsertOne) SetSignalConnected(v bool) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetSignalConnected(v)
	})
}

// UpdateSignalConnected sets the "signal_connected" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateSignalConnected() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateSignalConnected()
	})
}

// SetSSHEnabled sets the "ssh_enabled" field.
func (u *NetbirdUpsertOne) SetSSHEnabled(v bool) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetSSHEnabled(v)
	})
}

// UpdateSSHEnabled sets the "ssh_enabled" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateSSHEnabled() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateSSHEnabled()
	})
}

// SetPeersTotal sets the "peers_total" field.
func (u *NetbirdUpsertOne) SetPeersTotal(v int) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetPeersTotal(v)
	})
}

// AddPeersTotal adds v to the "peers_total" field.
func (u *NetbirdUpsertOne) AddPeersTotal(v int) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.AddPeersTotal(v)
	})
}

// UpdatePeersTotal sets the "peers_total" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdatePeersTotal() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdatePeersTotal()
	})
}

// ClearPeersTotal clears the value of the "peers_total" field.
func (u *NetbirdUpsertOne) ClearPeersTotal() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearPeersTotal()
	})
}

// SetPeersConnected sets the "peers_connected" field.
func (u *NetbirdUpsertOne) SetPeersConnected(v int) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetPeersConnected(v)
	})
}

// AddPeersConnected adds v to the "peers_connected" field.
func (u *NetbirdUpsertOne) AddPeersConnected(v int) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.AddPeersConnected(v)
	})
}

// UpdatePeersConnected sets the "peers_connected" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdatePeersConnected() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdatePeersConnected()
	})
}

// ClearPeersConnected clears the value of the "peers_connected" field.
func (u *NetbirdUpsertOne) ClearPeersConnected() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearPeersConnected()
	})
}

// SetProfilesAvailable sets the "profiles_available" field.
func (u *NetbirdUpsertOne) SetProfilesAvailable(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetProfilesAvailable(v)
	})
}

// UpdateProfilesAvailable sets the "profiles_available" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateProfilesAvailable() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateProfilesAvailable()
	})
}

// ClearProfilesAvailable clears the value of the "profiles_available" field.
func (u *NetbirdUpsertOne) ClearProfilesAvailable() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearProfilesAvailable()
	})
}

// SetDNSServer sets the "dns_server" field.
func (u *NetbirdUpsertOne) SetDNSServer(v string) *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetDNSServer(v)
	})
}

// UpdateDNSServer sets the "dns_server" field to the value that was provided on create.
func (u *NetbirdUpsertOne) UpdateDNSServer() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateDNSServer()
	})
}

// ClearDNSServer clears the value of the "dns_server" field.
func (u *NetbirdUpsertOne) ClearDNSServer() *NetbirdUpsertOne {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearDNSServer()
	})
}

// Exec executes the query.
func (u *NetbirdUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NetbirdCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NetbirdUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NetbirdUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NetbirdUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NetbirdCreateBulk is the builder for creating many Netbird entities in bulk.
type NetbirdCreateBulk struct {
	config
	err      error
	builders []*NetbirdCreate
	conflict []sql.ConflictOption
}

// Save creates the Netbird entities in the database.
func (ncb *NetbirdCreateBulk) Save(ctx context.Context) ([]*Netbird, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*Netbird, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NetbirdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ncb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NetbirdCreateBulk) SaveX(ctx context.Context) []*Netbird {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NetbirdCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NetbirdCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Netbird.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NetbirdUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (ncb *NetbirdCreateBulk) OnConflict(opts ...sql.ConflictOption) *NetbirdUpsertBulk {
	ncb.conflict = opts
	return &NetbirdUpsertBulk{
		create: ncb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Netbird.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ncb *NetbirdCreateBulk) OnConflictColumns(columns ...string) *NetbirdUpsertBulk {
	ncb.conflict = append(ncb.conflict, sql.ConflictColumns(columns...))
	return &NetbirdUpsertBulk{
		create: ncb,
	}
}

// NetbirdUpsertBulk is the builder for "upsert"-ing
// a bulk of Netbird nodes.
type NetbirdUpsertBulk struct {
	create *NetbirdCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Netbird.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NetbirdUpsertBulk) UpdateNewValues() *NetbirdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Netbird.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NetbirdUpsertBulk) Ignore() *NetbirdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NetbirdUpsertBulk) DoNothing() *NetbirdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NetbirdCreateBulk.OnConflict
// documentation for more info.
func (u *NetbirdUpsertBulk) Update(set func(*NetbirdUpsert)) *NetbirdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NetbirdUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *NetbirdUpsertBulk) SetVersion(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateVersion() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateVersion()
	})
}

// SetInstalled sets the "installed" field.
func (u *NetbirdUpsertBulk) SetInstalled(v bool) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetInstalled(v)
	})
}

// UpdateInstalled sets the "installed" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateInstalled() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateInstalled()
	})
}

// SetServiceStatus sets the "service_status" field.
func (u *NetbirdUpsertBulk) SetServiceStatus(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetServiceStatus(v)
	})
}

// UpdateServiceStatus sets the "service_status" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateServiceStatus() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateServiceStatus()
	})
}

// SetIP sets the "ip" field.
func (u *NetbirdUpsertBulk) SetIP(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateIP() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *NetbirdUpsertBulk) ClearIP() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearIP()
	})
}

// SetProfile sets the "profile" field.
func (u *NetbirdUpsertBulk) SetProfile(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateProfile() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateProfile()
	})
}

// ClearProfile clears the value of the "profile" field.
func (u *NetbirdUpsertBulk) ClearProfile() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearProfile()
	})
}

// SetManagementURL sets the "management_url" field.
func (u *NetbirdUpsertBulk) SetManagementURL(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetManagementURL(v)
	})
}

// UpdateManagementURL sets the "management_url" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateManagementURL() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateManagementURL()
	})
}

// ClearManagementURL clears the value of the "management_url" field.
func (u *NetbirdUpsertBulk) ClearManagementURL() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearManagementURL()
	})
}

// SetManagementConnected sets the "management_connected" field.
func (u *NetbirdUpsertBulk) SetManagementConnected(v bool) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetManagementConnected(v)
	})
}

// UpdateManagementConnected sets the "management_connected" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateManagementConnected() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateManagementConnected()
	})
}

// SetSignalURL sets the "signal_url" field.
func (u *NetbirdUpsertBulk) SetSignalURL(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetSignalURL(v)
	})
}

// UpdateSignalURL sets the "signal_url" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateSignalURL() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateSignalURL()
	})
}

// ClearSignalURL clears the value of the "signal_url" field.
func (u *NetbirdUpsertBulk) ClearSignalURL() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearSignalURL()
	})
}

// SetSignalConnected sets the "signal_connected" field.
func (u *NetbirdUpsertBulk) SetSignalConnected(v bool) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetSignalConnected(v)
	})
}

// UpdateSignalConnected sets the "signal_connected" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateSignalConnected() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateSignalConnected()
	})
}

// SetSSHEnabled sets the "ssh_enabled" field.
func (u *NetbirdUpsertBulk) SetSSHEnabled(v bool) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetSSHEnabled(v)
	})
}

// UpdateSSHEnabled sets the "ssh_enabled" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateSSHEnabled() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateSSHEnabled()
	})
}

// SetPeersTotal sets the "peers_total" field.
func (u *NetbirdUpsertBulk) SetPeersTotal(v int) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetPeersTotal(v)
	})
}

// AddPeersTotal adds v to the "peers_total" field.
func (u *NetbirdUpsertBulk) AddPeersTotal(v int) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.AddPeersTotal(v)
	})
}

// UpdatePeersTotal sets the "peers_total" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdatePeersTotal() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdatePeersTotal()
	})
}

// ClearPeersTotal clears the value of the "peers_total" field.
func (u *NetbirdUpsertBulk) ClearPeersTotal() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearPeersTotal()
	})
}

// SetPeersConnected sets the "peers_connected" field.
func (u *NetbirdUpsertBulk) SetPeersConnected(v int) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetPeersConnected(v)
	})
}

// AddPeersConnected adds v to the "peers_connected" field.
func (u *NetbirdUpsertBulk) AddPeersConnected(v int) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.AddPeersConnected(v)
	})
}

// UpdatePeersConnected sets the "peers_connected" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdatePeersConnected() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdatePeersConnected()
	})
}

// ClearPeersConnected clears the value of the "peers_connected" field.
func (u *NetbirdUpsertBulk) ClearPeersConnected() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearPeersConnected()
	})
}

// SetProfilesAvailable sets the "profiles_available" field.
func (u *NetbirdUpsertBulk) SetProfilesAvailable(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetProfilesAvailable(v)
	})
}

// UpdateProfilesAvailable sets the "profiles_available" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateProfilesAvailable() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateProfilesAvailable()
	})
}

// ClearProfilesAvailable clears the value of the "profiles_available" field.
func (u *NetbirdUpsertBulk) ClearProfilesAvailable() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearProfilesAvailable()
	})
}

// SetDNSServer sets the "dns_server" field.
func (u *NetbirdUpsertBulk) SetDNSServer(v string) *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.SetDNSServer(v)
	})
}

// UpdateDNSServer sets the "dns_server" field to the value that was provided on create.
func (u *NetbirdUpsertBulk) UpdateDNSServer() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.UpdateDNSServer()
	})
}

// ClearDNSServer clears the value of the "dns_server" field.
func (u *NetbirdUpsertBulk) ClearDNSServer() *NetbirdUpsertBulk {
	return u.Update(func(s *NetbirdUpsert) {
		s.ClearDNSServer()
	})
}

// Exec executes the query.
func (u *NetbirdUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NetbirdCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NetbirdCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NetbirdUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
