// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/metadata"
	"github.com/open-uem/ent/orgmetadata"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/tenant"
)

// OrgMetadataQuery is the builder for querying OrgMetadata entities.
type OrgMetadataQuery struct {
	config
	ctx          *QueryContext
	order        []orgmetadata.OrderOption
	inters       []Interceptor
	predicates   []predicate.OrgMetadata
	withMetadata *MetadataQuery
	withTenant   *TenantQuery
	withFKs      bool
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrgMetadataQuery builder.
func (_q *OrgMetadataQuery) Where(ps ...predicate.OrgMetadata) *OrgMetadataQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OrgMetadataQuery) Limit(limit int) *OrgMetadataQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OrgMetadataQuery) Offset(offset int) *OrgMetadataQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OrgMetadataQuery) Unique(unique bool) *OrgMetadataQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OrgMetadataQuery) Order(o ...orgmetadata.OrderOption) *OrgMetadataQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMetadata chains the current query on the "metadata" edge.
func (_q *OrgMetadataQuery) QueryMetadata() *MetadataQuery {
	query := (&MetadataClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orgmetadata.Table, orgmetadata.FieldID, selector),
			sqlgraph.To(metadata.Table, metadata.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, orgmetadata.MetadataTable, orgmetadata.MetadataColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *OrgMetadataQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orgmetadata.Table, orgmetadata.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orgmetadata.TenantTable, orgmetadata.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrgMetadata entity from the query.
// Returns a *NotFoundError when no OrgMetadata was found.
func (_q *OrgMetadataQuery) First(ctx context.Context) (*OrgMetadata, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orgmetadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OrgMetadataQuery) FirstX(ctx context.Context) *OrgMetadata {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrgMetadata ID from the query.
// Returns a *NotFoundError when no OrgMetadata ID was found.
func (_q *OrgMetadataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orgmetadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OrgMetadataQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrgMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrgMetadata entity is found.
// Returns a *NotFoundError when no OrgMetadata entities are found.
func (_q *OrgMetadataQuery) Only(ctx context.Context) (*OrgMetadata, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orgmetadata.Label}
	default:
		return nil, &NotSingularError{orgmetadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OrgMetadataQuery) OnlyX(ctx context.Context) *OrgMetadata {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrgMetadata ID in the query.
// Returns a *NotSingularError when more than one OrgMetadata ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OrgMetadataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orgmetadata.Label}
	default:
		err = &NotSingularError{orgmetadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OrgMetadataQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrgMetadataSlice.
func (_q *OrgMetadataQuery) All(ctx context.Context) ([]*OrgMetadata, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrgMetadata, *OrgMetadataQuery]()
	return withInterceptors[[]*OrgMetadata](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OrgMetadataQuery) AllX(ctx context.Context) []*OrgMetadata {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrgMetadata IDs.
func (_q *OrgMetadataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(orgmetadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OrgMetadataQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OrgMetadataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OrgMetadataQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OrgMetadataQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OrgMetadataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OrgMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrgMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OrgMetadataQuery) Clone() *OrgMetadataQuery {
	if _q == nil {
		return nil
	}
	return &OrgMetadataQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]orgmetadata.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.OrgMetadata{}, _q.predicates...),
		withMetadata: _q.withMetadata.Clone(),
		withTenant:   _q.withTenant.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithMetadata tells the query-builder to eager-load the nodes that are connected to
// the "metadata" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrgMetadataQuery) WithMetadata(opts ...func(*MetadataQuery)) *OrgMetadataQuery {
	query := (&MetadataClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMetadata = query
	return _q
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrgMetadataQuery) WithTenant(opts ...func(*TenantQuery)) *OrgMetadataQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrgMetadata.Query().
//		GroupBy(orgmetadata.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OrgMetadataQuery) GroupBy(field string, fields ...string) *OrgMetadataGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrgMetadataGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = orgmetadata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.OrgMetadata.Query().
//		Select(orgmetadata.FieldName).
//		Scan(ctx, &v)
func (_q *OrgMetadataQuery) Select(fields ...string) *OrgMetadataSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OrgMetadataSelect{OrgMetadataQuery: _q}
	sbuild.label = orgmetadata.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrgMetadataSelect configured with the given aggregations.
func (_q *OrgMetadataQuery) Aggregate(fns ...AggregateFunc) *OrgMetadataSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OrgMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !orgmetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OrgMetadataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrgMetadata, error) {
	var (
		nodes       = []*OrgMetadata{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMetadata != nil,
			_q.withTenant != nil,
		}
	)
	if _q.withTenant != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, orgmetadata.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrgMetadata).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrgMetadata{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMetadata; query != nil {
		if err := _q.loadMetadata(ctx, query, nodes,
			func(n *OrgMetadata) { n.Edges.Metadata = []*Metadata{} },
			func(n *OrgMetadata, e *Metadata) { n.Edges.Metadata = append(n.Edges.Metadata, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *OrgMetadata, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OrgMetadataQuery) loadMetadata(ctx context.Context, query *MetadataQuery, nodes []*OrgMetadata, init func(*OrgMetadata), assign func(*OrgMetadata, *Metadata)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*OrgMetadata)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Metadata(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(orgmetadata.MetadataColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.org_metadata_metadata
		if fk == nil {
			return fmt.Errorf(`foreign-key "org_metadata_metadata" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "org_metadata_metadata" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrgMetadataQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*OrgMetadata, init func(*OrgMetadata), assign func(*OrgMetadata, *Tenant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrgMetadata)
	for i := range nodes {
		if nodes[i].tenant_metadata == nil {
			continue
		}
		fk := *nodes[i].tenant_metadata
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_metadata" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *OrgMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OrgMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orgmetadata.Table, orgmetadata.Columns, sqlgraph.NewFieldSpec(orgmetadata.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orgmetadata.FieldID)
		for i := range fields {
			if fields[i] != orgmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OrgMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(orgmetadata.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = orgmetadata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *OrgMetadataQuery) Modify(modifiers ...func(s *sql.Selector)) *OrgMetadataSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// OrgMetadataGroupBy is the group-by builder for OrgMetadata entities.
type OrgMetadataGroupBy struct {
	selector
	build *OrgMetadataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OrgMetadataGroupBy) Aggregate(fns ...AggregateFunc) *OrgMetadataGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OrgMetadataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrgMetadataQuery, *OrgMetadataGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OrgMetadataGroupBy) sqlScan(ctx context.Context, root *OrgMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrgMetadataSelect is the builder for selecting fields of OrgMetadata entities.
type OrgMetadataSelect struct {
	*OrgMetadataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OrgMetadataSelect) Aggregate(fns ...AggregateFunc) *OrgMetadataSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OrgMetadataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrgMetadataQuery, *OrgMetadataSelect](ctx, _s.OrgMetadataQuery, _s, _s.inters, v)
}

func (_s *OrgMetadataSelect) sqlScan(ctx context.Context, root *OrgMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *OrgMetadataSelect) Modify(modifiers ...func(s *sql.Selector)) *OrgMetadataSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
