// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/profile"
	"github.com/open-uem/ent/profileissue"
	"github.com/open-uem/ent/taskreport"
)

// ProfileIssueUpdate is the builder for updating ProfileIssue entities.
type ProfileIssueUpdate struct {
	config
	hooks     []Hook
	mutation  *ProfileIssueMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProfileIssueUpdate builder.
func (_u *ProfileIssueUpdate) Where(ps ...predicate.ProfileIssue) *ProfileIssueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetError sets the "error" field.
func (_u *ProfileIssueUpdate) SetError(v string) *ProfileIssueUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ProfileIssueUpdate) SetNillableError(v *string) *ProfileIssueUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ProfileIssueUpdate) ClearError() *ProfileIssueUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetWhen sets the "when" field.
func (_u *ProfileIssueUpdate) SetWhen(v time.Time) *ProfileIssueUpdate {
	_u.mutation.SetWhen(v)
	return _u
}

// ClearWhen clears the value of the "when" field.
func (_u *ProfileIssueUpdate) ClearWhen() *ProfileIssueUpdate {
	_u.mutation.ClearWhen()
	return _u
}

// SetProfileID sets the "profile" edge to the Profile entity by ID.
func (_u *ProfileIssueUpdate) SetProfileID(id int) *ProfileIssueUpdate {
	_u.mutation.SetProfileID(id)
	return _u
}

// SetNillableProfileID sets the "profile" edge to the Profile entity by ID if the given value is not nil.
func (_u *ProfileIssueUpdate) SetNillableProfileID(id *int) *ProfileIssueUpdate {
	if id != nil {
		_u = _u.SetProfileID(*id)
	}
	return _u
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *ProfileIssueUpdate) SetProfile(v *Profile) *ProfileIssueUpdate {
	return _u.SetProfileID(v.ID)
}

// SetAgentsID sets the "agents" edge to the Agent entity by ID.
func (_u *ProfileIssueUpdate) SetAgentsID(id string) *ProfileIssueUpdate {
	_u.mutation.SetAgentsID(id)
	return _u
}

// SetNillableAgentsID sets the "agents" edge to the Agent entity by ID if the given value is not nil.
func (_u *ProfileIssueUpdate) SetNillableAgentsID(id *string) *ProfileIssueUpdate {
	if id != nil {
		_u = _u.SetAgentsID(*id)
	}
	return _u
}

// SetAgents sets the "agents" edge to the Agent entity.
func (_u *ProfileIssueUpdate) SetAgents(v *Agent) *ProfileIssueUpdate {
	return _u.SetAgentsID(v.ID)
}

// AddTasksreportIDs adds the "tasksreports" edge to the TaskReport entity by IDs.
func (_u *ProfileIssueUpdate) AddTasksreportIDs(ids ...int) *ProfileIssueUpdate {
	_u.mutation.AddTasksreportIDs(ids...)
	return _u
}

// AddTasksreports adds the "tasksreports" edges to the TaskReport entity.
func (_u *ProfileIssueUpdate) AddTasksreports(v ...*TaskReport) *ProfileIssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTasksreportIDs(ids...)
}

// Mutation returns the ProfileIssueMutation object of the builder.
func (_u *ProfileIssueUpdate) Mutation() *ProfileIssueMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *ProfileIssueUpdate) ClearProfile() *ProfileIssueUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// ClearAgents clears the "agents" edge to the Agent entity.
func (_u *ProfileIssueUpdate) ClearAgents() *ProfileIssueUpdate {
	_u.mutation.ClearAgents()
	return _u
}

// ClearTasksreports clears all "tasksreports" edges to the TaskReport entity.
func (_u *ProfileIssueUpdate) ClearTasksreports() *ProfileIssueUpdate {
	_u.mutation.ClearTasksreports()
	return _u
}

// RemoveTasksreportIDs removes the "tasksreports" edge to TaskReport entities by IDs.
func (_u *ProfileIssueUpdate) RemoveTasksreportIDs(ids ...int) *ProfileIssueUpdate {
	_u.mutation.RemoveTasksreportIDs(ids...)
	return _u
}

// RemoveTasksreports removes "tasksreports" edges to TaskReport entities.
func (_u *ProfileIssueUpdate) RemoveTasksreports(v ...*TaskReport) *ProfileIssueUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTasksreportIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProfileIssueUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileIssueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProfileIssueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileIssueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProfileIssueUpdate) defaults() {
	if _, ok := _u.mutation.When(); !ok && !_u.mutation.WhenCleared() {
		v := profileissue.UpdateDefaultWhen()
		_u.mutation.SetWhen(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProfileIssueUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProfileIssueUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProfileIssueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(profileissue.Table, profileissue.Columns, sqlgraph.NewFieldSpec(profileissue.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(profileissue.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(profileissue.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.When(); ok {
		_spec.SetField(profileissue.FieldWhen, field.TypeTime, value)
	}
	if _u.mutation.WhenCleared() {
		_spec.ClearField(profileissue.FieldWhen, field.TypeTime)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileissue.ProfileTable,
			Columns: []string{profileissue.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileissue.ProfileTable,
			Columns: []string{profileissue.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileissue.AgentsTable,
			Columns: []string{profileissue.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileissue.AgentsTable,
			Columns: []string{profileissue.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksreportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profileissue.TasksreportsTable,
			Columns: []string{profileissue.TasksreportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksreportsIDs(); len(nodes) > 0 && !_u.mutation.TasksreportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profileissue.TasksreportsTable,
			Columns: []string{profileissue.TasksreportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksreportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profileissue.TasksreportsTable,
			Columns: []string{profileissue.TasksreportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileissue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProfileIssueUpdateOne is the builder for updating a single ProfileIssue entity.
type ProfileIssueUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProfileIssueMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetError sets the "error" field.
func (_u *ProfileIssueUpdateOne) SetError(v string) *ProfileIssueUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *ProfileIssueUpdateOne) SetNillableError(v *string) *ProfileIssueUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *ProfileIssueUpdateOne) ClearError() *ProfileIssueUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetWhen sets the "when" field.
func (_u *ProfileIssueUpdateOne) SetWhen(v time.Time) *ProfileIssueUpdateOne {
	_u.mutation.SetWhen(v)
	return _u
}

// ClearWhen clears the value of the "when" field.
func (_u *ProfileIssueUpdateOne) ClearWhen() *ProfileIssueUpdateOne {
	_u.mutation.ClearWhen()
	return _u
}

// SetProfileID sets the "profile" edge to the Profile entity by ID.
func (_u *ProfileIssueUpdateOne) SetProfileID(id int) *ProfileIssueUpdateOne {
	_u.mutation.SetProfileID(id)
	return _u
}

// SetNillableProfileID sets the "profile" edge to the Profile entity by ID if the given value is not nil.
func (_u *ProfileIssueUpdateOne) SetNillableProfileID(id *int) *ProfileIssueUpdateOne {
	if id != nil {
		_u = _u.SetProfileID(*id)
	}
	return _u
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *ProfileIssueUpdateOne) SetProfile(v *Profile) *ProfileIssueUpdateOne {
	return _u.SetProfileID(v.ID)
}

// SetAgentsID sets the "agents" edge to the Agent entity by ID.
func (_u *ProfileIssueUpdateOne) SetAgentsID(id string) *ProfileIssueUpdateOne {
	_u.mutation.SetAgentsID(id)
	return _u
}

// SetNillableAgentsID sets the "agents" edge to the Agent entity by ID if the given value is not nil.
func (_u *ProfileIssueUpdateOne) SetNillableAgentsID(id *string) *ProfileIssueUpdateOne {
	if id != nil {
		_u = _u.SetAgentsID(*id)
	}
	return _u
}

// SetAgents sets the "agents" edge to the Agent entity.
func (_u *ProfileIssueUpdateOne) SetAgents(v *Agent) *ProfileIssueUpdateOne {
	return _u.SetAgentsID(v.ID)
}

// AddTasksreportIDs adds the "tasksreports" edge to the TaskReport entity by IDs.
func (_u *ProfileIssueUpdateOne) AddTasksreportIDs(ids ...int) *ProfileIssueUpdateOne {
	_u.mutation.AddTasksreportIDs(ids...)
	return _u
}

// AddTasksreports adds the "tasksreports" edges to the TaskReport entity.
func (_u *ProfileIssueUpdateOne) AddTasksreports(v ...*TaskReport) *ProfileIssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTasksreportIDs(ids...)
}

// Mutation returns the ProfileIssueMutation object of the builder.
func (_u *ProfileIssueUpdateOne) Mutation() *ProfileIssueMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *ProfileIssueUpdateOne) ClearProfile() *ProfileIssueUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// ClearAgents clears the "agents" edge to the Agent entity.
func (_u *ProfileIssueUpdateOne) ClearAgents() *ProfileIssueUpdateOne {
	_u.mutation.ClearAgents()
	return _u
}

// ClearTasksreports clears all "tasksreports" edges to the TaskReport entity.
func (_u *ProfileIssueUpdateOne) ClearTasksreports() *ProfileIssueUpdateOne {
	_u.mutation.ClearTasksreports()
	return _u
}

// RemoveTasksreportIDs removes the "tasksreports" edge to TaskReport entities by IDs.
func (_u *ProfileIssueUpdateOne) RemoveTasksreportIDs(ids ...int) *ProfileIssueUpdateOne {
	_u.mutation.RemoveTasksreportIDs(ids...)
	return _u
}

// RemoveTasksreports removes "tasksreports" edges to TaskReport entities.
func (_u *ProfileIssueUpdateOne) RemoveTasksreports(v ...*TaskReport) *ProfileIssueUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTasksreportIDs(ids...)
}

// Where appends a list predicates to the ProfileIssueUpdate builder.
func (_u *ProfileIssueUpdateOne) Where(ps ...predicate.ProfileIssue) *ProfileIssueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProfileIssueUpdateOne) Select(field string, fields ...string) *ProfileIssueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProfileIssue entity.
func (_u *ProfileIssueUpdateOne) Save(ctx context.Context) (*ProfileIssue, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProfileIssueUpdateOne) SaveX(ctx context.Context) *ProfileIssue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProfileIssueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProfileIssueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProfileIssueUpdateOne) defaults() {
	if _, ok := _u.mutation.When(); !ok && !_u.mutation.WhenCleared() {
		v := profileissue.UpdateDefaultWhen()
		_u.mutation.SetWhen(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProfileIssueUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProfileIssueUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProfileIssueUpdateOne) sqlSave(ctx context.Context) (_node *ProfileIssue, err error) {
	_spec := sqlgraph.NewUpdateSpec(profileissue.Table, profileissue.Columns, sqlgraph.NewFieldSpec(profileissue.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProfileIssue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profileissue.FieldID)
		for _, f := range fields {
			if !profileissue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profileissue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(profileissue.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(profileissue.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.When(); ok {
		_spec.SetField(profileissue.FieldWhen, field.TypeTime, value)
	}
	if _u.mutation.WhenCleared() {
		_spec.ClearField(profileissue.FieldWhen, field.TypeTime)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileissue.ProfileTable,
			Columns: []string{profileissue.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   profileissue.ProfileTable,
			Columns: []string{profileissue.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileissue.AgentsTable,
			Columns: []string{profileissue.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   profileissue.AgentsTable,
			Columns: []string{profileissue.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksreportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profileissue.TasksreportsTable,
			Columns: []string{profileissue.TasksreportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksreportsIDs(); len(nodes) > 0 && !_u.mutation.TasksreportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profileissue.TasksreportsTable,
			Columns: []string{profileissue.TasksreportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksreportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profileissue.TasksreportsTable,
			Columns: []string{profileissue.TasksreportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ProfileIssue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileissue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
