// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/enrollmenttoken"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/profile"
	"github.com/open-uem/ent/site"
	"github.com/open-uem/ent/tenant"
)

// SiteQuery is the builder for querying Site entities.
type SiteQuery struct {
	config
	ctx                  *QueryContext
	order                []site.OrderOption
	inters               []Interceptor
	predicates           []predicate.Site
	withTenant           *TenantQuery
	withAgents           *AgentQuery
	withProfiles         *ProfileQuery
	withEnrollmentTokens *EnrollmentTokenQuery
	withFKs              bool
	modifiers            []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SiteQuery builder.
func (sq *SiteQuery) Where(ps ...predicate.Site) *SiteQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SiteQuery) Limit(limit int) *SiteQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SiteQuery) Offset(offset int) *SiteQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SiteQuery) Unique(unique bool) *SiteQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SiteQuery) Order(o ...site.OrderOption) *SiteQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryTenant chains the current query on the "tenant" edge.
func (sq *SiteQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(site.Table, site.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, site.TenantTable, site.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgents chains the current query on the "agents" edge.
func (sq *SiteQuery) QueryAgents() *AgentQuery {
	query := (&AgentClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(site.Table, site.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, site.AgentsTable, site.AgentsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProfiles chains the current query on the "profiles" edge.
func (sq *SiteQuery) QueryProfiles() *ProfileQuery {
	query := (&ProfileClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(site.Table, site.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, site.ProfilesTable, site.ProfilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEnrollmentTokens chains the current query on the "enrollment_tokens" edge.
func (sq *SiteQuery) QueryEnrollmentTokens() *EnrollmentTokenQuery {
	query := (&EnrollmentTokenClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(site.Table, site.FieldID, selector),
			sqlgraph.To(enrollmenttoken.Table, enrollmenttoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, site.EnrollmentTokensTable, site.EnrollmentTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Site entity from the query.
// Returns a *NotFoundError when no Site was found.
func (sq *SiteQuery) First(ctx context.Context) (*Site, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{site.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SiteQuery) FirstX(ctx context.Context) *Site {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Site ID from the query.
// Returns a *NotFoundError when no Site ID was found.
func (sq *SiteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{site.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SiteQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Site entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Site entity is found.
// Returns a *NotFoundError when no Site entities are found.
func (sq *SiteQuery) Only(ctx context.Context) (*Site, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{site.Label}
	default:
		return nil, &NotSingularError{site.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SiteQuery) OnlyX(ctx context.Context) *Site {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Site ID in the query.
// Returns a *NotSingularError when more than one Site ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SiteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{site.Label}
	default:
		err = &NotSingularError{site.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SiteQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Sites.
func (sq *SiteQuery) All(ctx context.Context) ([]*Site, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryAll)
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Site, *SiteQuery]()
	return withInterceptors[[]*Site](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SiteQuery) AllX(ctx context.Context) []*Site {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Site IDs.
func (sq *SiteQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryIDs)
	if err = sq.Select(site.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SiteQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SiteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryCount)
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SiteQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SiteQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SiteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, ent.OpQueryExist)
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SiteQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SiteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SiteQuery) Clone() *SiteQuery {
	if sq == nil {
		return nil
	}
	return &SiteQuery{
		config:               sq.config,
		ctx:                  sq.ctx.Clone(),
		order:                append([]site.OrderOption{}, sq.order...),
		inters:               append([]Interceptor{}, sq.inters...),
		predicates:           append([]predicate.Site{}, sq.predicates...),
		withTenant:           sq.withTenant.Clone(),
		withAgents:           sq.withAgents.Clone(),
		withProfiles:         sq.withProfiles.Clone(),
		withEnrollmentTokens: sq.withEnrollmentTokens.Clone(),
		// clone intermediate query.
		sql:       sq.sql.Clone(),
		path:      sq.path,
		modifiers: append([]func(*sql.Selector){}, sq.modifiers...),
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SiteQuery) WithTenant(opts ...func(*TenantQuery)) *SiteQuery {
	query := (&TenantClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withTenant = query
	return sq
}

// WithAgents tells the query-builder to eager-load the nodes that are connected to
// the "agents" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SiteQuery) WithAgents(opts ...func(*AgentQuery)) *SiteQuery {
	query := (&AgentClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withAgents = query
	return sq
}

// WithProfiles tells the query-builder to eager-load the nodes that are connected to
// the "profiles" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SiteQuery) WithProfiles(opts ...func(*ProfileQuery)) *SiteQuery {
	query := (&ProfileClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withProfiles = query
	return sq
}

// WithEnrollmentTokens tells the query-builder to eager-load the nodes that are connected to
// the "enrollment_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SiteQuery) WithEnrollmentTokens(opts ...func(*EnrollmentTokenQuery)) *SiteQuery {
	query := (&EnrollmentTokenClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withEnrollmentTokens = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Site.Query().
//		GroupBy(site.FieldDescription).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SiteQuery) GroupBy(field string, fields ...string) *SiteGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SiteGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = site.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description,omitempty"`
//	}
//
//	client.Site.Query().
//		Select(site.FieldDescription).
//		Scan(ctx, &v)
func (sq *SiteQuery) Select(fields ...string) *SiteSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SiteSelect{SiteQuery: sq}
	sbuild.label = site.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SiteSelect configured with the given aggregations.
func (sq *SiteQuery) Aggregate(fns ...AggregateFunc) *SiteSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SiteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !site.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SiteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Site, error) {
	var (
		nodes       = []*Site{}
		withFKs     = sq.withFKs
		_spec       = sq.querySpec()
		loadedTypes = [4]bool{
			sq.withTenant != nil,
			sq.withAgents != nil,
			sq.withProfiles != nil,
			sq.withEnrollmentTokens != nil,
		}
	)
	if sq.withTenant != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, site.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Site).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Site{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withTenant; query != nil {
		if err := sq.loadTenant(ctx, query, nodes, nil,
			func(n *Site, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := sq.withAgents; query != nil {
		if err := sq.loadAgents(ctx, query, nodes,
			func(n *Site) { n.Edges.Agents = []*Agent{} },
			func(n *Site, e *Agent) { n.Edges.Agents = append(n.Edges.Agents, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withProfiles; query != nil {
		if err := sq.loadProfiles(ctx, query, nodes,
			func(n *Site) { n.Edges.Profiles = []*Profile{} },
			func(n *Site, e *Profile) { n.Edges.Profiles = append(n.Edges.Profiles, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withEnrollmentTokens; query != nil {
		if err := sq.loadEnrollmentTokens(ctx, query, nodes,
			func(n *Site) { n.Edges.EnrollmentTokens = []*EnrollmentToken{} },
			func(n *Site, e *EnrollmentToken) { n.Edges.EnrollmentTokens = append(n.Edges.EnrollmentTokens, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SiteQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*Site, init func(*Site), assign func(*Site, *Tenant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Site)
	for i := range nodes {
		if nodes[i].tenant_sites == nil {
			continue
		}
		fk := *nodes[i].tenant_sites
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_sites" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sq *SiteQuery) loadAgents(ctx context.Context, query *AgentQuery, nodes []*Site, init func(*Site), assign func(*Site, *Agent)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Site)
	nids := make(map[string]map[*Site]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(site.AgentsTable)
		s.Join(joinT).On(s.C(agent.FieldID), joinT.C(site.AgentsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(site.AgentsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(site.AgentsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*Site]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Agent](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "agents" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (sq *SiteQuery) loadProfiles(ctx context.Context, query *ProfileQuery, nodes []*Site, init func(*Site), assign func(*Site, *Profile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Site)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Profile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(site.ProfilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.site_profiles
		if fk == nil {
			return fmt.Errorf(`foreign-key "site_profiles" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "site_profiles" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *SiteQuery) loadEnrollmentTokens(ctx context.Context, query *EnrollmentTokenQuery, nodes []*Site, init func(*Site), assign func(*Site, *EnrollmentToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Site)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.EnrollmentToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(site.EnrollmentTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.site_enrollment_tokens
		if fk == nil {
			return fmt.Errorf(`foreign-key "site_enrollment_tokens" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "site_enrollment_tokens" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sq *SiteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SiteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for i := range fields {
			if fields[i] != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SiteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(site.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = site.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range sq.modifiers {
		m(selector)
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sq *SiteQuery) Modify(modifiers ...func(s *sql.Selector)) *SiteSelect {
	sq.modifiers = append(sq.modifiers, modifiers...)
	return sq.Select()
}

// SiteGroupBy is the group-by builder for Site entities.
type SiteGroupBy struct {
	selector
	build *SiteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SiteGroupBy) Aggregate(fns ...AggregateFunc) *SiteGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SiteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, ent.OpQueryGroupBy)
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SiteQuery, *SiteGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SiteGroupBy) sqlScan(ctx context.Context, root *SiteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SiteSelect is the builder for selecting fields of Site entities.
type SiteSelect struct {
	*SiteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SiteSelect) Aggregate(fns ...AggregateFunc) *SiteSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SiteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, ent.OpQuerySelect)
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SiteQuery, *SiteSelect](ctx, ss.SiteQuery, ss, ss.inters, v)
}

func (ss *SiteSelect) sqlScan(ctx context.Context, root *SiteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ss *SiteSelect) Modify(modifiers ...func(s *sql.Selector)) *SiteSelect {
	ss.modifiers = append(ss.modifiers, modifiers...)
	return ss
}
