// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/enrollmenttoken"
	"github.com/open-uem/ent/netbirdsettings"
	"github.com/open-uem/ent/orgmetadata"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/rustdesk"
	"github.com/open-uem/ent/settings"
	"github.com/open-uem/ent/site"
	"github.com/open-uem/ent/tag"
	"github.com/open-uem/ent/tenant"
	"github.com/open-uem/ent/usertenant"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks     []Hook
	mutation  *TenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TenantUpdate builder.
func (tu *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetDescription sets the "description" field.
func (tu *TenantUpdate) SetDescription(s string) *TenantUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableDescription(s *string) *TenantUpdate {
	if s != nil {
		tu.SetDescription(*s)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *TenantUpdate) ClearDescription() *TenantUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// SetIsDefault sets the "is_default" field.
func (tu *TenantUpdate) SetIsDefault(b bool) *TenantUpdate {
	tu.mutation.SetIsDefault(b)
	return tu
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableIsDefault(b *bool) *TenantUpdate {
	if b != nil {
		tu.SetIsDefault(*b)
	}
	return tu
}

// ClearIsDefault clears the value of the "is_default" field.
func (tu *TenantUpdate) ClearIsDefault() *TenantUpdate {
	tu.mutation.ClearIsDefault()
	return tu
}

// SetOidcOrgID sets the "oidc_org_id" field.
func (tu *TenantUpdate) SetOidcOrgID(s string) *TenantUpdate {
	tu.mutation.SetOidcOrgID(s)
	return tu
}

// SetNillableOidcOrgID sets the "oidc_org_id" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableOidcOrgID(s *string) *TenantUpdate {
	if s != nil {
		tu.SetOidcOrgID(*s)
	}
	return tu
}

// ClearOidcOrgID clears the value of the "oidc_org_id" field.
func (tu *TenantUpdate) ClearOidcOrgID() *TenantUpdate {
	tu.mutation.ClearOidcOrgID()
	return tu
}

// SetOidcDefaultRole sets the "oidc_default_role" field.
func (tu *TenantUpdate) SetOidcDefaultRole(tdr tenant.OidcDefaultRole) *TenantUpdate {
	tu.mutation.SetOidcDefaultRole(tdr)
	return tu
}

// SetNillableOidcDefaultRole sets the "oidc_default_role" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableOidcDefaultRole(tdr *tenant.OidcDefaultRole) *TenantUpdate {
	if tdr != nil {
		tu.SetOidcDefaultRole(*tdr)
	}
	return tu
}

// ClearOidcDefaultRole clears the value of the "oidc_default_role" field.
func (tu *TenantUpdate) ClearOidcDefaultRole() *TenantUpdate {
	tu.mutation.ClearOidcDefaultRole()
	return tu
}

// SetCreated sets the "created" field.
func (tu *TenantUpdate) SetCreated(t time.Time) *TenantUpdate {
	tu.mutation.SetCreated(t)
	return tu
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableCreated(t *time.Time) *TenantUpdate {
	if t != nil {
		tu.SetCreated(*t)
	}
	return tu
}

// ClearCreated clears the value of the "created" field.
func (tu *TenantUpdate) ClearCreated() *TenantUpdate {
	tu.mutation.ClearCreated()
	return tu
}

// SetModified sets the "modified" field.
func (tu *TenantUpdate) SetModified(t time.Time) *TenantUpdate {
	tu.mutation.SetModified(t)
	return tu
}

// ClearModified clears the value of the "modified" field.
func (tu *TenantUpdate) ClearModified() *TenantUpdate {
	tu.mutation.ClearModified()
	return tu
}

// AddSiteIDs adds the "sites" edge to the Site entity by IDs.
func (tu *TenantUpdate) AddSiteIDs(ids ...int) *TenantUpdate {
	tu.mutation.AddSiteIDs(ids...)
	return tu
}

// AddSites adds the "sites" edges to the Site entity.
func (tu *TenantUpdate) AddSites(s ...*Site) *TenantUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.AddSiteIDs(ids...)
}

// SetSettingsID sets the "settings" edge to the Settings entity by ID.
func (tu *TenantUpdate) SetSettingsID(id int) *TenantUpdate {
	tu.mutation.SetSettingsID(id)
	return tu
}

// SetNillableSettingsID sets the "settings" edge to the Settings entity by ID if the given value is not nil.
func (tu *TenantUpdate) SetNillableSettingsID(id *int) *TenantUpdate {
	if id != nil {
		tu = tu.SetSettingsID(*id)
	}
	return tu
}

// SetSettings sets the "settings" edge to the Settings entity.
func (tu *TenantUpdate) SetSettings(s *Settings) *TenantUpdate {
	return tu.SetSettingsID(s.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (tu *TenantUpdate) AddTagIDs(ids ...int) *TenantUpdate {
	tu.mutation.AddTagIDs(ids...)
	return tu
}

// AddTags adds the "tags" edges to the Tag entity.
func (tu *TenantUpdate) AddTags(t ...*Tag) *TenantUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddTagIDs(ids...)
}

// AddMetadatumIDs adds the "metadata" edge to the OrgMetadata entity by IDs.
func (tu *TenantUpdate) AddMetadatumIDs(ids ...int) *TenantUpdate {
	tu.mutation.AddMetadatumIDs(ids...)
	return tu
}

// AddMetadata adds the "metadata" edges to the OrgMetadata entity.
func (tu *TenantUpdate) AddMetadata(o ...*OrgMetadata) *TenantUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tu.AddMetadatumIDs(ids...)
}

// AddRustdeskIDs adds the "rustdesk" edge to the Rustdesk entity by IDs.
func (tu *TenantUpdate) AddRustdeskIDs(ids ...int) *TenantUpdate {
	tu.mutation.AddRustdeskIDs(ids...)
	return tu
}

// AddRustdesk adds the "rustdesk" edges to the Rustdesk entity.
func (tu *TenantUpdate) AddRustdesk(r ...*Rustdesk) *TenantUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tu.AddRustdeskIDs(ids...)
}

// SetNetbirdID sets the "netbird" edge to the NetbirdSettings entity by ID.
func (tu *TenantUpdate) SetNetbirdID(id int) *TenantUpdate {
	tu.mutation.SetNetbirdID(id)
	return tu
}

// SetNillableNetbirdID sets the "netbird" edge to the NetbirdSettings entity by ID if the given value is not nil.
func (tu *TenantUpdate) SetNillableNetbirdID(id *int) *TenantUpdate {
	if id != nil {
		tu = tu.SetNetbirdID(*id)
	}
	return tu
}

// SetNetbird sets the "netbird" edge to the NetbirdSettings entity.
func (tu *TenantUpdate) SetNetbird(n *NetbirdSettings) *TenantUpdate {
	return tu.SetNetbirdID(n.ID)
}

// AddUserTenantIDs adds the "user_tenants" edge to the UserTenant entity by IDs.
func (tu *TenantUpdate) AddUserTenantIDs(ids ...int) *TenantUpdate {
	tu.mutation.AddUserTenantIDs(ids...)
	return tu
}

// AddUserTenants adds the "user_tenants" edges to the UserTenant entity.
func (tu *TenantUpdate) AddUserTenants(u ...*UserTenant) *TenantUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tu.AddUserTenantIDs(ids...)
}

// AddEnrollmentTokenIDs adds the "enrollment_tokens" edge to the EnrollmentToken entity by IDs.
func (tu *TenantUpdate) AddEnrollmentTokenIDs(ids ...int) *TenantUpdate {
	tu.mutation.AddEnrollmentTokenIDs(ids...)
	return tu
}

// AddEnrollmentTokens adds the "enrollment_tokens" edges to the EnrollmentToken entity.
func (tu *TenantUpdate) AddEnrollmentTokens(e ...*EnrollmentToken) *TenantUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tu.AddEnrollmentTokenIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (tu *TenantUpdate) Mutation() *TenantMutation {
	return tu.mutation
}

// ClearSites clears all "sites" edges to the Site entity.
func (tu *TenantUpdate) ClearSites() *TenantUpdate {
	tu.mutation.ClearSites()
	return tu
}

// RemoveSiteIDs removes the "sites" edge to Site entities by IDs.
func (tu *TenantUpdate) RemoveSiteIDs(ids ...int) *TenantUpdate {
	tu.mutation.RemoveSiteIDs(ids...)
	return tu
}

// RemoveSites removes "sites" edges to Site entities.
func (tu *TenantUpdate) RemoveSites(s ...*Site) *TenantUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.RemoveSiteIDs(ids...)
}

// ClearSettings clears the "settings" edge to the Settings entity.
func (tu *TenantUpdate) ClearSettings() *TenantUpdate {
	tu.mutation.ClearSettings()
	return tu
}

// ClearTags clears all "tags" edges to the Tag entity.
func (tu *TenantUpdate) ClearTags() *TenantUpdate {
	tu.mutation.ClearTags()
	return tu
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (tu *TenantUpdate) RemoveTagIDs(ids ...int) *TenantUpdate {
	tu.mutation.RemoveTagIDs(ids...)
	return tu
}

// RemoveTags removes "tags" edges to Tag entities.
func (tu *TenantUpdate) RemoveTags(t ...*Tag) *TenantUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveTagIDs(ids...)
}

// ClearMetadata clears all "metadata" edges to the OrgMetadata entity.
func (tu *TenantUpdate) ClearMetadata() *TenantUpdate {
	tu.mutation.ClearMetadata()
	return tu
}

// RemoveMetadatumIDs removes the "metadata" edge to OrgMetadata entities by IDs.
func (tu *TenantUpdate) RemoveMetadatumIDs(ids ...int) *TenantUpdate {
	tu.mutation.RemoveMetadatumIDs(ids...)
	return tu
}

// RemoveMetadata removes "metadata" edges to OrgMetadata entities.
func (tu *TenantUpdate) RemoveMetadata(o ...*OrgMetadata) *TenantUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tu.RemoveMetadatumIDs(ids...)
}

// ClearRustdesk clears all "rustdesk" edges to the Rustdesk entity.
func (tu *TenantUpdate) ClearRustdesk() *TenantUpdate {
	tu.mutation.ClearRustdesk()
	return tu
}

// RemoveRustdeskIDs removes the "rustdesk" edge to Rustdesk entities by IDs.
func (tu *TenantUpdate) RemoveRustdeskIDs(ids ...int) *TenantUpdate {
	tu.mutation.RemoveRustdeskIDs(ids...)
	return tu
}

// RemoveRustdesk removes "rustdesk" edges to Rustdesk entities.
func (tu *TenantUpdate) RemoveRustdesk(r ...*Rustdesk) *TenantUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tu.RemoveRustdeskIDs(ids...)
}

// ClearNetbird clears the "netbird" edge to the NetbirdSettings entity.
func (tu *TenantUpdate) ClearNetbird() *TenantUpdate {
	tu.mutation.ClearNetbird()
	return tu
}

// ClearUserTenants clears all "user_tenants" edges to the UserTenant entity.
func (tu *TenantUpdate) ClearUserTenants() *TenantUpdate {
	tu.mutation.ClearUserTenants()
	return tu
}

// RemoveUserTenantIDs removes the "user_tenants" edge to UserTenant entities by IDs.
func (tu *TenantUpdate) RemoveUserTenantIDs(ids ...int) *TenantUpdate {
	tu.mutation.RemoveUserTenantIDs(ids...)
	return tu
}

// RemoveUserTenants removes "user_tenants" edges to UserTenant entities.
func (tu *TenantUpdate) RemoveUserTenants(u ...*UserTenant) *TenantUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tu.RemoveUserTenantIDs(ids...)
}

// ClearEnrollmentTokens clears all "enrollment_tokens" edges to the EnrollmentToken entity.
func (tu *TenantUpdate) ClearEnrollmentTokens() *TenantUpdate {
	tu.mutation.ClearEnrollmentTokens()
	return tu
}

// RemoveEnrollmentTokenIDs removes the "enrollment_tokens" edge to EnrollmentToken entities by IDs.
func (tu *TenantUpdate) RemoveEnrollmentTokenIDs(ids ...int) *TenantUpdate {
	tu.mutation.RemoveEnrollmentTokenIDs(ids...)
	return tu
}

// RemoveEnrollmentTokens removes "enrollment_tokens" edges to EnrollmentToken entities.
func (tu *TenantUpdate) RemoveEnrollmentTokens(e ...*EnrollmentToken) *TenantUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tu.RemoveEnrollmentTokenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TenantUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TenantUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TenantUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TenantUpdate) defaults() {
	if _, ok := tu.mutation.Modified(); !ok && !tu.mutation.ModifiedCleared() {
		v := tenant.UpdateDefaultModified()
		tu.mutation.SetModified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TenantUpdate) check() error {
	if v, ok := tu.mutation.OidcDefaultRole(); ok {
		if err := tenant.OidcDefaultRoleValidator(v); err != nil {
			return &ValidationError{Name: "oidc_default_role", err: fmt.Errorf(`ent: validator failed for field "Tenant.oidc_default_role": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tu *TenantUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantUpdate {
	tu.modifiers = append(tu.modifiers, modifiers...)
	return tu
}

func (tu *TenantUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if tu.mutation.DescriptionCleared() {
		_spec.ClearField(tenant.FieldDescription, field.TypeString)
	}
	if value, ok := tu.mutation.IsDefault(); ok {
		_spec.SetField(tenant.FieldIsDefault, field.TypeBool, value)
	}
	if tu.mutation.IsDefaultCleared() {
		_spec.ClearField(tenant.FieldIsDefault, field.TypeBool)
	}
	if value, ok := tu.mutation.OidcOrgID(); ok {
		_spec.SetField(tenant.FieldOidcOrgID, field.TypeString, value)
	}
	if tu.mutation.OidcOrgIDCleared() {
		_spec.ClearField(tenant.FieldOidcOrgID, field.TypeString)
	}
	if value, ok := tu.mutation.OidcDefaultRole(); ok {
		_spec.SetField(tenant.FieldOidcDefaultRole, field.TypeEnum, value)
	}
	if tu.mutation.OidcDefaultRoleCleared() {
		_spec.ClearField(tenant.FieldOidcDefaultRole, field.TypeEnum)
	}
	if value, ok := tu.mutation.Created(); ok {
		_spec.SetField(tenant.FieldCreated, field.TypeTime, value)
	}
	if tu.mutation.CreatedCleared() {
		_spec.ClearField(tenant.FieldCreated, field.TypeTime)
	}
	if value, ok := tu.mutation.Modified(); ok {
		_spec.SetField(tenant.FieldModified, field.TypeTime, value)
	}
	if tu.mutation.ModifiedCleared() {
		_spec.ClearField(tenant.FieldModified, field.TypeTime)
	}
	if tu.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SitesTable,
			Columns: []string{tenant.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedSitesIDs(); len(nodes) > 0 && !tu.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SitesTable,
			Columns: []string{tenant.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SitesTable,
			Columns: []string{tenant.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TagsTable,
			Columns: []string{tenant.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedTagsIDs(); len(nodes) > 0 && !tu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TagsTable,
			Columns: []string{tenant.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TagsTable,
			Columns: []string{tenant.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.MetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MetadataTable,
			Columns: []string{tenant.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgmetadata.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedMetadataIDs(); len(nodes) > 0 && !tu.mutation.MetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MetadataTable,
			Columns: []string{tenant.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgmetadata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.MetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MetadataTable,
			Columns: []string{tenant.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgmetadata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.RustdeskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tenant.RustdeskTable,
			Columns: tenant.RustdeskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rustdesk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedRustdeskIDs(); len(nodes) > 0 && !tu.mutation.RustdeskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tenant.RustdeskTable,
			Columns: tenant.RustdeskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rustdesk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RustdeskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tenant.RustdeskTable,
			Columns: tenant.RustdeskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rustdesk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.NetbirdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tenant.NetbirdTable,
			Columns: []string{tenant.NetbirdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.NetbirdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tenant.NetbirdTable,
			Columns: []string{tenant.NetbirdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.UserTenantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tenant.UserTenantsTable,
			Columns: []string{tenant.UserTenantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedUserTenantsIDs(); len(nodes) > 0 && !tu.mutation.UserTenantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tenant.UserTenantsTable,
			Columns: []string{tenant.UserTenantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.UserTenantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tenant.UserTenantsTable,
			Columns: []string{tenant.UserTenantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.EnrollmentTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EnrollmentTokensTable,
			Columns: []string{tenant.EnrollmentTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedEnrollmentTokensIDs(); len(nodes) > 0 && !tu.mutation.EnrollmentTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EnrollmentTokensTable,
			Columns: []string{tenant.EnrollmentTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.EnrollmentTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EnrollmentTokensTable,
			Columns: []string{tenant.EnrollmentTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDescription sets the "description" field.
func (tuo *TenantUpdateOne) SetDescription(s string) *TenantUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableDescription(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetDescription(*s)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *TenantUpdateOne) ClearDescription() *TenantUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// SetIsDefault sets the "is_default" field.
func (tuo *TenantUpdateOne) SetIsDefault(b bool) *TenantUpdateOne {
	tuo.mutation.SetIsDefault(b)
	return tuo
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableIsDefault(b *bool) *TenantUpdateOne {
	if b != nil {
		tuo.SetIsDefault(*b)
	}
	return tuo
}

// ClearIsDefault clears the value of the "is_default" field.
func (tuo *TenantUpdateOne) ClearIsDefault() *TenantUpdateOne {
	tuo.mutation.ClearIsDefault()
	return tuo
}

// SetOidcOrgID sets the "oidc_org_id" field.
func (tuo *TenantUpdateOne) SetOidcOrgID(s string) *TenantUpdateOne {
	tuo.mutation.SetOidcOrgID(s)
	return tuo
}

// SetNillableOidcOrgID sets the "oidc_org_id" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableOidcOrgID(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetOidcOrgID(*s)
	}
	return tuo
}

// ClearOidcOrgID clears the value of the "oidc_org_id" field.
func (tuo *TenantUpdateOne) ClearOidcOrgID() *TenantUpdateOne {
	tuo.mutation.ClearOidcOrgID()
	return tuo
}

// SetOidcDefaultRole sets the "oidc_default_role" field.
func (tuo *TenantUpdateOne) SetOidcDefaultRole(tdr tenant.OidcDefaultRole) *TenantUpdateOne {
	tuo.mutation.SetOidcDefaultRole(tdr)
	return tuo
}

// SetNillableOidcDefaultRole sets the "oidc_default_role" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableOidcDefaultRole(tdr *tenant.OidcDefaultRole) *TenantUpdateOne {
	if tdr != nil {
		tuo.SetOidcDefaultRole(*tdr)
	}
	return tuo
}

// ClearOidcDefaultRole clears the value of the "oidc_default_role" field.
func (tuo *TenantUpdateOne) ClearOidcDefaultRole() *TenantUpdateOne {
	tuo.mutation.ClearOidcDefaultRole()
	return tuo
}

// SetCreated sets the "created" field.
func (tuo *TenantUpdateOne) SetCreated(t time.Time) *TenantUpdateOne {
	tuo.mutation.SetCreated(t)
	return tuo
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableCreated(t *time.Time) *TenantUpdateOne {
	if t != nil {
		tuo.SetCreated(*t)
	}
	return tuo
}

// ClearCreated clears the value of the "created" field.
func (tuo *TenantUpdateOne) ClearCreated() *TenantUpdateOne {
	tuo.mutation.ClearCreated()
	return tuo
}

// SetModified sets the "modified" field.
func (tuo *TenantUpdateOne) SetModified(t time.Time) *TenantUpdateOne {
	tuo.mutation.SetModified(t)
	return tuo
}

// ClearModified clears the value of the "modified" field.
func (tuo *TenantUpdateOne) ClearModified() *TenantUpdateOne {
	tuo.mutation.ClearModified()
	return tuo
}

// AddSiteIDs adds the "sites" edge to the Site entity by IDs.
func (tuo *TenantUpdateOne) AddSiteIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.AddSiteIDs(ids...)
	return tuo
}

// AddSites adds the "sites" edges to the Site entity.
func (tuo *TenantUpdateOne) AddSites(s ...*Site) *TenantUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.AddSiteIDs(ids...)
}

// SetSettingsID sets the "settings" edge to the Settings entity by ID.
func (tuo *TenantUpdateOne) SetSettingsID(id int) *TenantUpdateOne {
	tuo.mutation.SetSettingsID(id)
	return tuo
}

// SetNillableSettingsID sets the "settings" edge to the Settings entity by ID if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableSettingsID(id *int) *TenantUpdateOne {
	if id != nil {
		tuo = tuo.SetSettingsID(*id)
	}
	return tuo
}

// SetSettings sets the "settings" edge to the Settings entity.
func (tuo *TenantUpdateOne) SetSettings(s *Settings) *TenantUpdateOne {
	return tuo.SetSettingsID(s.ID)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (tuo *TenantUpdateOne) AddTagIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.AddTagIDs(ids...)
	return tuo
}

// AddTags adds the "tags" edges to the Tag entity.
func (tuo *TenantUpdateOne) AddTags(t ...*Tag) *TenantUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddTagIDs(ids...)
}

// AddMetadatumIDs adds the "metadata" edge to the OrgMetadata entity by IDs.
func (tuo *TenantUpdateOne) AddMetadatumIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.AddMetadatumIDs(ids...)
	return tuo
}

// AddMetadata adds the "metadata" edges to the OrgMetadata entity.
func (tuo *TenantUpdateOne) AddMetadata(o ...*OrgMetadata) *TenantUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tuo.AddMetadatumIDs(ids...)
}

// AddRustdeskIDs adds the "rustdesk" edge to the Rustdesk entity by IDs.
func (tuo *TenantUpdateOne) AddRustdeskIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.AddRustdeskIDs(ids...)
	return tuo
}

// AddRustdesk adds the "rustdesk" edges to the Rustdesk entity.
func (tuo *TenantUpdateOne) AddRustdesk(r ...*Rustdesk) *TenantUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tuo.AddRustdeskIDs(ids...)
}

// SetNetbirdID sets the "netbird" edge to the NetbirdSettings entity by ID.
func (tuo *TenantUpdateOne) SetNetbirdID(id int) *TenantUpdateOne {
	tuo.mutation.SetNetbirdID(id)
	return tuo
}

// SetNillableNetbirdID sets the "netbird" edge to the NetbirdSettings entity by ID if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableNetbirdID(id *int) *TenantUpdateOne {
	if id != nil {
		tuo = tuo.SetNetbirdID(*id)
	}
	return tuo
}

// SetNetbird sets the "netbird" edge to the NetbirdSettings entity.
func (tuo *TenantUpdateOne) SetNetbird(n *NetbirdSettings) *TenantUpdateOne {
	return tuo.SetNetbirdID(n.ID)
}

// AddUserTenantIDs adds the "user_tenants" edge to the UserTenant entity by IDs.
func (tuo *TenantUpdateOne) AddUserTenantIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.AddUserTenantIDs(ids...)
	return tuo
}

// AddUserTenants adds the "user_tenants" edges to the UserTenant entity.
func (tuo *TenantUpdateOne) AddUserTenants(u ...*UserTenant) *TenantUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tuo.AddUserTenantIDs(ids...)
}

// AddEnrollmentTokenIDs adds the "enrollment_tokens" edge to the EnrollmentToken entity by IDs.
func (tuo *TenantUpdateOne) AddEnrollmentTokenIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.AddEnrollmentTokenIDs(ids...)
	return tuo
}

// AddEnrollmentTokens adds the "enrollment_tokens" edges to the EnrollmentToken entity.
func (tuo *TenantUpdateOne) AddEnrollmentTokens(e ...*EnrollmentToken) *TenantUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tuo.AddEnrollmentTokenIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (tuo *TenantUpdateOne) Mutation() *TenantMutation {
	return tuo.mutation
}

// ClearSites clears all "sites" edges to the Site entity.
func (tuo *TenantUpdateOne) ClearSites() *TenantUpdateOne {
	tuo.mutation.ClearSites()
	return tuo
}

// RemoveSiteIDs removes the "sites" edge to Site entities by IDs.
func (tuo *TenantUpdateOne) RemoveSiteIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.RemoveSiteIDs(ids...)
	return tuo
}

// RemoveSites removes "sites" edges to Site entities.
func (tuo *TenantUpdateOne) RemoveSites(s ...*Site) *TenantUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.RemoveSiteIDs(ids...)
}

// ClearSettings clears the "settings" edge to the Settings entity.
func (tuo *TenantUpdateOne) ClearSettings() *TenantUpdateOne {
	tuo.mutation.ClearSettings()
	return tuo
}

// ClearTags clears all "tags" edges to the Tag entity.
func (tuo *TenantUpdateOne) ClearTags() *TenantUpdateOne {
	tuo.mutation.ClearTags()
	return tuo
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (tuo *TenantUpdateOne) RemoveTagIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.RemoveTagIDs(ids...)
	return tuo
}

// RemoveTags removes "tags" edges to Tag entities.
func (tuo *TenantUpdateOne) RemoveTags(t ...*Tag) *TenantUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveTagIDs(ids...)
}

// ClearMetadata clears all "metadata" edges to the OrgMetadata entity.
func (tuo *TenantUpdateOne) ClearMetadata() *TenantUpdateOne {
	tuo.mutation.ClearMetadata()
	return tuo
}

// RemoveMetadatumIDs removes the "metadata" edge to OrgMetadata entities by IDs.
func (tuo *TenantUpdateOne) RemoveMetadatumIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.RemoveMetadatumIDs(ids...)
	return tuo
}

// RemoveMetadata removes "metadata" edges to OrgMetadata entities.
func (tuo *TenantUpdateOne) RemoveMetadata(o ...*OrgMetadata) *TenantUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tuo.RemoveMetadatumIDs(ids...)
}

// ClearRustdesk clears all "rustdesk" edges to the Rustdesk entity.
func (tuo *TenantUpdateOne) ClearRustdesk() *TenantUpdateOne {
	tuo.mutation.ClearRustdesk()
	return tuo
}

// RemoveRustdeskIDs removes the "rustdesk" edge to Rustdesk entities by IDs.
func (tuo *TenantUpdateOne) RemoveRustdeskIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.RemoveRustdeskIDs(ids...)
	return tuo
}

// RemoveRustdesk removes "rustdesk" edges to Rustdesk entities.
func (tuo *TenantUpdateOne) RemoveRustdesk(r ...*Rustdesk) *TenantUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tuo.RemoveRustdeskIDs(ids...)
}

// ClearNetbird clears the "netbird" edge to the NetbirdSettings entity.
func (tuo *TenantUpdateOne) ClearNetbird() *TenantUpdateOne {
	tuo.mutation.ClearNetbird()
	return tuo
}

// ClearUserTenants clears all "user_tenants" edges to the UserTenant entity.
func (tuo *TenantUpdateOne) ClearUserTenants() *TenantUpdateOne {
	tuo.mutation.ClearUserTenants()
	return tuo
}

// RemoveUserTenantIDs removes the "user_tenants" edge to UserTenant entities by IDs.
func (tuo *TenantUpdateOne) RemoveUserTenantIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.RemoveUserTenantIDs(ids...)
	return tuo
}

// RemoveUserTenants removes "user_tenants" edges to UserTenant entities.
func (tuo *TenantUpdateOne) RemoveUserTenants(u ...*UserTenant) *TenantUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return tuo.RemoveUserTenantIDs(ids...)
}

// ClearEnrollmentTokens clears all "enrollment_tokens" edges to the EnrollmentToken entity.
func (tuo *TenantUpdateOne) ClearEnrollmentTokens() *TenantUpdateOne {
	tuo.mutation.ClearEnrollmentTokens()
	return tuo
}

// RemoveEnrollmentTokenIDs removes the "enrollment_tokens" edge to EnrollmentToken entities by IDs.
func (tuo *TenantUpdateOne) RemoveEnrollmentTokenIDs(ids ...int) *TenantUpdateOne {
	tuo.mutation.RemoveEnrollmentTokenIDs(ids...)
	return tuo
}

// RemoveEnrollmentTokens removes "enrollment_tokens" edges to EnrollmentToken entities.
func (tuo *TenantUpdateOne) RemoveEnrollmentTokens(e ...*EnrollmentToken) *TenantUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tuo.RemoveEnrollmentTokenIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (tuo *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tenant entity.
func (tuo *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TenantUpdateOne) defaults() {
	if _, ok := tuo.mutation.Modified(); !ok && !tuo.mutation.ModifiedCleared() {
		v := tenant.UpdateDefaultModified()
		tuo.mutation.SetModified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TenantUpdateOne) check() error {
	if v, ok := tuo.mutation.OidcDefaultRole(); ok {
		if err := tenant.OidcDefaultRoleValidator(v); err != nil {
			return &ValidationError{Name: "oidc_default_role", err: fmt.Errorf(`ent: validator failed for field "Tenant.oidc_default_role": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tuo *TenantUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantUpdateOne {
	tuo.modifiers = append(tuo.modifiers, modifiers...)
	return tuo
}

func (tuo *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.ClearField(tenant.FieldDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.IsDefault(); ok {
		_spec.SetField(tenant.FieldIsDefault, field.TypeBool, value)
	}
	if tuo.mutation.IsDefaultCleared() {
		_spec.ClearField(tenant.FieldIsDefault, field.TypeBool)
	}
	if value, ok := tuo.mutation.OidcOrgID(); ok {
		_spec.SetField(tenant.FieldOidcOrgID, field.TypeString, value)
	}
	if tuo.mutation.OidcOrgIDCleared() {
		_spec.ClearField(tenant.FieldOidcOrgID, field.TypeString)
	}
	if value, ok := tuo.mutation.OidcDefaultRole(); ok {
		_spec.SetField(tenant.FieldOidcDefaultRole, field.TypeEnum, value)
	}
	if tuo.mutation.OidcDefaultRoleCleared() {
		_spec.ClearField(tenant.FieldOidcDefaultRole, field.TypeEnum)
	}
	if value, ok := tuo.mutation.Created(); ok {
		_spec.SetField(tenant.FieldCreated, field.TypeTime, value)
	}
	if tuo.mutation.CreatedCleared() {
		_spec.ClearField(tenant.FieldCreated, field.TypeTime)
	}
	if value, ok := tuo.mutation.Modified(); ok {
		_spec.SetField(tenant.FieldModified, field.TypeTime, value)
	}
	if tuo.mutation.ModifiedCleared() {
		_spec.ClearField(tenant.FieldModified, field.TypeTime)
	}
	if tuo.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SitesTable,
			Columns: []string{tenant.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedSitesIDs(); len(nodes) > 0 && !tuo.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SitesTable,
			Columns: []string{tenant.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.SitesTable,
			Columns: []string{tenant.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TagsTable,
			Columns: []string{tenant.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !tuo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TagsTable,
			Columns: []string{tenant.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.TagsTable,
			Columns: []string{tenant.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.MetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MetadataTable,
			Columns: []string{tenant.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgmetadata.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedMetadataIDs(); len(nodes) > 0 && !tuo.mutation.MetadataCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MetadataTable,
			Columns: []string{tenant.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgmetadata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.MetadataIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MetadataTable,
			Columns: []string{tenant.MetadataColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgmetadata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.RustdeskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tenant.RustdeskTable,
			Columns: tenant.RustdeskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rustdesk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedRustdeskIDs(); len(nodes) > 0 && !tuo.mutation.RustdeskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tenant.RustdeskTable,
			Columns: tenant.RustdeskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rustdesk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RustdeskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tenant.RustdeskTable,
			Columns: tenant.RustdeskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rustdesk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.NetbirdCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tenant.NetbirdTable,
			Columns: []string{tenant.NetbirdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.NetbirdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tenant.NetbirdTable,
			Columns: []string{tenant.NetbirdColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.UserTenantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tenant.UserTenantsTable,
			Columns: []string{tenant.UserTenantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedUserTenantsIDs(); len(nodes) > 0 && !tuo.mutation.UserTenantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tenant.UserTenantsTable,
			Columns: []string{tenant.UserTenantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.UserTenantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tenant.UserTenantsTable,
			Columns: []string{tenant.UserTenantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.EnrollmentTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EnrollmentTokensTable,
			Columns: []string{tenant.EnrollmentTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedEnrollmentTokensIDs(); len(nodes) > 0 && !tuo.mutation.EnrollmentTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EnrollmentTokensTable,
			Columns: []string{tenant.EnrollmentTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.EnrollmentTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EnrollmentTokensTable,
			Columns: []string{tenant.EnrollmentTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollmenttoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tuo.modifiers...)
	_node = &Tenant{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
