// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/recoverycode"
	"github.com/open-uem/ent/sessions"
	"github.com/open-uem/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks     []Hook
	mutation  *UserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdate) ClearEmail() *UserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdate) SetPhone(v string) *UserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePhone(v *string) *UserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdate) ClearPhone() *UserUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetCountry sets the "country" field.
func (_u *UserUpdate) SetCountry(v string) *UserUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCountry(v *string) *UserUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *UserUpdate) ClearCountry() *UserUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *UserUpdate) SetEmailVerified(v bool) *UserUpdate {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmailVerified(v *bool) *UserUpdate {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetRegister sets the "register" field.
func (_u *UserUpdate) SetRegister(v string) *UserUpdate {
	_u.mutation.SetRegister(v)
	return _u
}

// SetNillableRegister sets the "register" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRegister(v *string) *UserUpdate {
	if v != nil {
		_u.SetRegister(*v)
	}
	return _u
}

// SetCertClearPassword sets the "cert_clear_password" field.
func (_u *UserUpdate) SetCertClearPassword(v string) *UserUpdate {
	_u.mutation.SetCertClearPassword(v)
	return _u
}

// SetNillableCertClearPassword sets the "cert_clear_password" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCertClearPassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetCertClearPassword(*v)
	}
	return _u
}

// ClearCertClearPassword clears the value of the "cert_clear_password" field.
func (_u *UserUpdate) ClearCertClearPassword() *UserUpdate {
	_u.mutation.ClearCertClearPassword()
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *UserUpdate) SetExpiry(v time.Time) *UserUpdate {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *UserUpdate) SetNillableExpiry(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// ClearExpiry clears the value of the "expiry" field.
func (_u *UserUpdate) ClearExpiry() *UserUpdate {
	_u.mutation.ClearExpiry()
	return _u
}

// SetOpenid sets the "openid" field.
func (_u *UserUpdate) SetOpenid(v bool) *UserUpdate {
	_u.mutation.SetOpenid(v)
	return _u
}

// SetNillableOpenid sets the "openid" field if the given value is not nil.
func (_u *UserUpdate) SetNillableOpenid(v *bool) *UserUpdate {
	if v != nil {
		_u.SetOpenid(*v)
	}
	return _u
}

// ClearOpenid clears the value of the "openid" field.
func (_u *UserUpdate) ClearOpenid() *UserUpdate {
	_u.mutation.ClearOpenid()
	return _u
}

// SetPasswd sets the "passwd" field.
func (_u *UserUpdate) SetPasswd(v bool) *UserUpdate {
	_u.mutation.SetPasswd(v)
	return _u
}

// SetNillablePasswd sets the "passwd" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswd(v *bool) *UserUpdate {
	if v != nil {
		_u.SetPasswd(*v)
	}
	return _u
}

// ClearPasswd clears the value of the "passwd" field.
func (_u *UserUpdate) ClearPasswd() *UserUpdate {
	_u.mutation.ClearPasswd()
	return _u
}

// SetUse2fa sets the "use2fa" field.
func (_u *UserUpdate) SetUse2fa(v bool) *UserUpdate {
	_u.mutation.SetUse2fa(v)
	return _u
}

// SetNillableUse2fa sets the "use2fa" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUse2fa(v *bool) *UserUpdate {
	if v != nil {
		_u.SetUse2fa(*v)
	}
	return _u
}

// ClearUse2fa clears the value of the "use2fa" field.
func (_u *UserUpdate) ClearUse2fa() *UserUpdate {
	_u.mutation.ClearUse2fa()
	return _u
}

// SetCreated sets the "created" field.
func (_u *UserUpdate) SetCreated(v time.Time) *UserUpdate {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreated(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// ClearCreated clears the value of the "created" field.
func (_u *UserUpdate) ClearCreated() *UserUpdate {
	_u.mutation.ClearCreated()
	return _u
}

// SetModified sets the "modified" field.
func (_u *UserUpdate) SetModified(v time.Time) *UserUpdate {
	_u.mutation.SetModified(v)
	return _u
}

// ClearModified clears the value of the "modified" field.
func (_u *UserUpdate) ClearModified() *UserUpdate {
	_u.mutation.ClearModified()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserUpdate) SetAccessToken(v string) *UserUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAccessToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UserUpdate) ClearAccessToken() *UserUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserUpdate) SetRefreshToken(v string) *UserUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRefreshToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserUpdate) ClearRefreshToken() *UserUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetIDToken sets the "id_token" field.
func (_u *UserUpdate) SetIDToken(v string) *UserUpdate {
	_u.mutation.SetIDToken(v)
	return _u
}

// SetNillableIDToken sets the "id_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIDToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetIDToken(*v)
	}
	return _u
}

// ClearIDToken clears the value of the "id_token" field.
func (_u *UserUpdate) ClearIDToken() *UserUpdate {
	_u.mutation.ClearIDToken()
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *UserUpdate) SetTokenType(v string) *UserUpdate {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTokenType(v *string) *UserUpdate {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// ClearTokenType clears the value of the "token_type" field.
func (_u *UserUpdate) ClearTokenType() *UserUpdate {
	_u.mutation.ClearTokenType()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *UserUpdate) SetTokenExpiry(v int) *UserUpdate {
	_u.mutation.ResetTokenExpiry()
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTokenExpiry(v *int) *UserUpdate {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// AddTokenExpiry adds value to the "token_expiry" field.
func (_u *UserUpdate) AddTokenExpiry(v int) *UserUpdate {
	_u.mutation.AddTokenExpiry(v)
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *UserUpdate) ClearTokenExpiry() *UserUpdate {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetHash sets the "hash" field.
func (_u *UserUpdate) SetHash(v string) *UserUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillableHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *UserUpdate) ClearHash() *UserUpdate {
	_u.mutation.ClearHash()
	return _u
}

// SetTotpSecret sets the "totp_secret" field.
func (_u *UserUpdate) SetTotpSecret(v string) *UserUpdate {
	_u.mutation.SetTotpSecret(v)
	return _u
}

// SetNillableTotpSecret sets the "totp_secret" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTotpSecret(v *string) *UserUpdate {
	if v != nil {
		_u.SetTotpSecret(*v)
	}
	return _u
}

// ClearTotpSecret clears the value of the "totp_secret" field.
func (_u *UserUpdate) ClearTotpSecret() *UserUpdate {
	_u.mutation.ClearTotpSecret()
	return _u
}

// SetTotpSecretConfirmed sets the "totp_secret_confirmed" field.
func (_u *UserUpdate) SetTotpSecretConfirmed(v bool) *UserUpdate {
	_u.mutation.SetTotpSecretConfirmed(v)
	return _u
}

// SetNillableTotpSecretConfirmed sets the "totp_secret_confirmed" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTotpSecretConfirmed(v *bool) *UserUpdate {
	if v != nil {
		_u.SetTotpSecretConfirmed(*v)
	}
	return _u
}

// ClearTotpSecretConfirmed clears the value of the "totp_secret_confirmed" field.
func (_u *UserUpdate) ClearTotpSecretConfirmed() *UserUpdate {
	_u.mutation.ClearTotpSecretConfirmed()
	return _u
}

// SetForgotPasswordCode sets the "forgot_password_code" field.
func (_u *UserUpdate) SetForgotPasswordCode(v string) *UserUpdate {
	_u.mutation.SetForgotPasswordCode(v)
	return _u
}

// SetNillableForgotPasswordCode sets the "forgot_password_code" field if the given value is not nil.
func (_u *UserUpdate) SetNillableForgotPasswordCode(v *string) *UserUpdate {
	if v != nil {
		_u.SetForgotPasswordCode(*v)
	}
	return _u
}

// ClearForgotPasswordCode clears the value of the "forgot_password_code" field.
func (_u *UserUpdate) ClearForgotPasswordCode() *UserUpdate {
	_u.mutation.ClearForgotPasswordCode()
	return _u
}

// SetForgotPasswordCodeExpiresAt sets the "forgot_password_code_expires_at" field.
func (_u *UserUpdate) SetForgotPasswordCodeExpiresAt(v time.Time) *UserUpdate {
	_u.mutation.SetForgotPasswordCodeExpiresAt(v)
	return _u
}

// SetNillableForgotPasswordCodeExpiresAt sets the "forgot_password_code_expires_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableForgotPasswordCodeExpiresAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetForgotPasswordCodeExpiresAt(*v)
	}
	return _u
}

// ClearForgotPasswordCodeExpiresAt clears the value of the "forgot_password_code_expires_at" field.
func (_u *UserUpdate) ClearForgotPasswordCodeExpiresAt() *UserUpdate {
	_u.mutation.ClearForgotPasswordCodeExpiresAt()
	return _u
}

// SetNewUserToken sets the "new_user_token" field.
func (_u *UserUpdate) SetNewUserToken(v string) *UserUpdate {
	_u.mutation.SetNewUserToken(v)
	return _u
}

// SetNillableNewUserToken sets the "new_user_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNewUserToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetNewUserToken(*v)
	}
	return _u
}

// ClearNewUserToken clears the value of the "new_user_token" field.
func (_u *UserUpdate) ClearNewUserToken() *UserUpdate {
	_u.mutation.ClearNewUserToken()
	return _u
}

// AddSessionIDs adds the "sessions" edge to the Sessions entity by IDs.
func (_u *UserUpdate) AddSessionIDs(ids ...string) *UserUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Sessions entity.
func (_u *UserUpdate) AddSessions(v ...*Sessions) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddRecoverycodeIDs adds the "recoverycodes" edge to the RecoveryCode entity by IDs.
func (_u *UserUpdate) AddRecoverycodeIDs(ids ...int) *UserUpdate {
	_u.mutation.AddRecoverycodeIDs(ids...)
	return _u
}

// AddRecoverycodes adds the "recoverycodes" edges to the RecoveryCode entity.
func (_u *UserUpdate) AddRecoverycodes(v ...*RecoveryCode) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecoverycodeIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSessions clears all "sessions" edges to the Sessions entity.
func (_u *UserUpdate) ClearSessions() *UserUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Sessions entities by IDs.
func (_u *UserUpdate) RemoveSessionIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Sessions entities.
func (_u *UserUpdate) RemoveSessions(v ...*Sessions) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearRecoverycodes clears all "recoverycodes" edges to the RecoveryCode entity.
func (_u *UserUpdate) ClearRecoverycodes() *UserUpdate {
	_u.mutation.ClearRecoverycodes()
	return _u
}

// RemoveRecoverycodeIDs removes the "recoverycodes" edge to RecoveryCode entities by IDs.
func (_u *UserUpdate) RemoveRecoverycodeIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveRecoverycodeIDs(ids...)
	return _u
}

// RemoveRecoverycodes removes "recoverycodes" edges to RecoveryCode entities.
func (_u *UserUpdate) RemoveRecoverycodes(v ...*RecoveryCode) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecoverycodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.Modified(); !ok && !_u.mutation.ModifiedCleared() {
		v := user.UpdateDefaultModified()
		_u.mutation.SetModified(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(user.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(user.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(user.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Register(); ok {
		_spec.SetField(user.FieldRegister, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertClearPassword(); ok {
		_spec.SetField(user.FieldCertClearPassword, field.TypeString, value)
	}
	if _u.mutation.CertClearPasswordCleared() {
		_spec.ClearField(user.FieldCertClearPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(user.FieldExpiry, field.TypeTime, value)
	}
	if _u.mutation.ExpiryCleared() {
		_spec.ClearField(user.FieldExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.Openid(); ok {
		_spec.SetField(user.FieldOpenid, field.TypeBool, value)
	}
	if _u.mutation.OpenidCleared() {
		_spec.ClearField(user.FieldOpenid, field.TypeBool)
	}
	if value, ok := _u.mutation.Passwd(); ok {
		_spec.SetField(user.FieldPasswd, field.TypeBool, value)
	}
	if _u.mutation.PasswdCleared() {
		_spec.ClearField(user.FieldPasswd, field.TypeBool)
	}
	if value, ok := _u.mutation.Use2fa(); ok {
		_spec.SetField(user.FieldUse2fa, field.TypeBool, value)
	}
	if _u.mutation.Use2faCleared() {
		_spec.ClearField(user.FieldUse2fa, field.TypeBool)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(user.FieldCreated, field.TypeTime, value)
	}
	if _u.mutation.CreatedCleared() {
		_spec.ClearField(user.FieldCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.Modified(); ok {
		_spec.SetField(user.FieldModified, field.TypeTime, value)
	}
	if _u.mutation.ModifiedCleared() {
		_spec.ClearField(user.FieldModified, field.TypeTime)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(user.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(user.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(user.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(user.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.IDToken(); ok {
		_spec.SetField(user.FieldIDToken, field.TypeString, value)
	}
	if _u.mutation.IDTokenCleared() {
		_spec.ClearField(user.FieldIDToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(user.FieldTokenType, field.TypeString, value)
	}
	if _u.mutation.TokenTypeCleared() {
		_spec.ClearField(user.FieldTokenType, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(user.FieldTokenExpiry, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenExpiry(); ok {
		_spec.AddField(user.FieldTokenExpiry, field.TypeInt, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(user.FieldTokenExpiry, field.TypeInt)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(user.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(user.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.TotpSecret(); ok {
		_spec.SetField(user.FieldTotpSecret, field.TypeString, value)
	}
	if _u.mutation.TotpSecretCleared() {
		_spec.ClearField(user.FieldTotpSecret, field.TypeString)
	}
	if value, ok := _u.mutation.TotpSecretConfirmed(); ok {
		_spec.SetField(user.FieldTotpSecretConfirmed, field.TypeBool, value)
	}
	if _u.mutation.TotpSecretConfirmedCleared() {
		_spec.ClearField(user.FieldTotpSecretConfirmed, field.TypeBool)
	}
	if value, ok := _u.mutation.ForgotPasswordCode(); ok {
		_spec.SetField(user.FieldForgotPasswordCode, field.TypeString, value)
	}
	if _u.mutation.ForgotPasswordCodeCleared() {
		_spec.ClearField(user.FieldForgotPasswordCode, field.TypeString)
	}
	if value, ok := _u.mutation.ForgotPasswordCodeExpiresAt(); ok {
		_spec.SetField(user.FieldForgotPasswordCodeExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ForgotPasswordCodeExpiresAtCleared() {
		_spec.ClearField(user.FieldForgotPasswordCodeExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NewUserToken(); ok {
		_spec.SetField(user.FieldNewUserToken, field.TypeString, value)
	}
	if _u.mutation.NewUserTokenCleared() {
		_spec.ClearField(user.FieldNewUserToken, field.TypeString)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessions.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessions.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessions.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecoverycodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecoverycodesTable,
			Columns: []string{user.RecoverycodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverycode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecoverycodesIDs(); len(nodes) > 0 && !_u.mutation.RecoverycodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecoverycodesTable,
			Columns: []string{user.RecoverycodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverycode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecoverycodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecoverycodesTable,
			Columns: []string{user.RecoverycodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverycode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdateOne) ClearEmail() *UserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdateOne) SetPhone(v string) *UserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePhone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdateOne) ClearPhone() *UserUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetCountry sets the "country" field.
func (_u *UserUpdateOne) SetCountry(v string) *UserUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCountry(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *UserUpdateOne) ClearCountry() *UserUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *UserUpdateOne) SetEmailVerified(v bool) *UserUpdateOne {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmailVerified(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetRegister sets the "register" field.
func (_u *UserUpdateOne) SetRegister(v string) *UserUpdateOne {
	_u.mutation.SetRegister(v)
	return _u
}

// SetNillableRegister sets the "register" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRegister(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRegister(*v)
	}
	return _u
}

// SetCertClearPassword sets the "cert_clear_password" field.
func (_u *UserUpdateOne) SetCertClearPassword(v string) *UserUpdateOne {
	_u.mutation.SetCertClearPassword(v)
	return _u
}

// SetNillableCertClearPassword sets the "cert_clear_password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCertClearPassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCertClearPassword(*v)
	}
	return _u
}

// ClearCertClearPassword clears the value of the "cert_clear_password" field.
func (_u *UserUpdateOne) ClearCertClearPassword() *UserUpdateOne {
	_u.mutation.ClearCertClearPassword()
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *UserUpdateOne) SetExpiry(v time.Time) *UserUpdateOne {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableExpiry(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// ClearExpiry clears the value of the "expiry" field.
func (_u *UserUpdateOne) ClearExpiry() *UserUpdateOne {
	_u.mutation.ClearExpiry()
	return _u
}

// SetOpenid sets the "openid" field.
func (_u *UserUpdateOne) SetOpenid(v bool) *UserUpdateOne {
	_u.mutation.SetOpenid(v)
	return _u
}

// SetNillableOpenid sets the "openid" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableOpenid(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetOpenid(*v)
	}
	return _u
}

// ClearOpenid clears the value of the "openid" field.
func (_u *UserUpdateOne) ClearOpenid() *UserUpdateOne {
	_u.mutation.ClearOpenid()
	return _u
}

// SetPasswd sets the "passwd" field.
func (_u *UserUpdateOne) SetPasswd(v bool) *UserUpdateOne {
	_u.mutation.SetPasswd(v)
	return _u
}

// SetNillablePasswd sets the "passwd" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswd(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetPasswd(*v)
	}
	return _u
}

// ClearPasswd clears the value of the "passwd" field.
func (_u *UserUpdateOne) ClearPasswd() *UserUpdateOne {
	_u.mutation.ClearPasswd()
	return _u
}

// SetUse2fa sets the "use2fa" field.
func (_u *UserUpdateOne) SetUse2fa(v bool) *UserUpdateOne {
	_u.mutation.SetUse2fa(v)
	return _u
}

// SetNillableUse2fa sets the "use2fa" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUse2fa(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetUse2fa(*v)
	}
	return _u
}

// ClearUse2fa clears the value of the "use2fa" field.
func (_u *UserUpdateOne) ClearUse2fa() *UserUpdateOne {
	_u.mutation.ClearUse2fa()
	return _u
}

// SetCreated sets the "created" field.
func (_u *UserUpdateOne) SetCreated(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreated(v)
	return _u
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreated(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreated(*v)
	}
	return _u
}

// ClearCreated clears the value of the "created" field.
func (_u *UserUpdateOne) ClearCreated() *UserUpdateOne {
	_u.mutation.ClearCreated()
	return _u
}

// SetModified sets the "modified" field.
func (_u *UserUpdateOne) SetModified(v time.Time) *UserUpdateOne {
	_u.mutation.SetModified(v)
	return _u
}

// ClearModified clears the value of the "modified" field.
func (_u *UserUpdateOne) ClearModified() *UserUpdateOne {
	_u.mutation.ClearModified()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserUpdateOne) SetAccessToken(v string) *UserUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAccessToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UserUpdateOne) ClearAccessToken() *UserUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserUpdateOne) SetRefreshToken(v string) *UserUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRefreshToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserUpdateOne) ClearRefreshToken() *UserUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetIDToken sets the "id_token" field.
func (_u *UserUpdateOne) SetIDToken(v string) *UserUpdateOne {
	_u.mutation.SetIDToken(v)
	return _u
}

// SetNillableIDToken sets the "id_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIDToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetIDToken(*v)
	}
	return _u
}

// ClearIDToken clears the value of the "id_token" field.
func (_u *UserUpdateOne) ClearIDToken() *UserUpdateOne {
	_u.mutation.ClearIDToken()
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *UserUpdateOne) SetTokenType(v string) *UserUpdateOne {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTokenType(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// ClearTokenType clears the value of the "token_type" field.
func (_u *UserUpdateOne) ClearTokenType() *UserUpdateOne {
	_u.mutation.ClearTokenType()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *UserUpdateOne) SetTokenExpiry(v int) *UserUpdateOne {
	_u.mutation.ResetTokenExpiry()
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTokenExpiry(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// AddTokenExpiry adds value to the "token_expiry" field.
func (_u *UserUpdateOne) AddTokenExpiry(v int) *UserUpdateOne {
	_u.mutation.AddTokenExpiry(v)
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *UserUpdateOne) ClearTokenExpiry() *UserUpdateOne {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetHash sets the "hash" field.
func (_u *UserUpdateOne) SetHash(v string) *UserUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// ClearHash clears the value of the "hash" field.
func (_u *UserUpdateOne) ClearHash() *UserUpdateOne {
	_u.mutation.ClearHash()
	return _u
}

// SetTotpSecret sets the "totp_secret" field.
func (_u *UserUpdateOne) SetTotpSecret(v string) *UserUpdateOne {
	_u.mutation.SetTotpSecret(v)
	return _u
}

// SetNillableTotpSecret sets the "totp_secret" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTotpSecret(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTotpSecret(*v)
	}
	return _u
}

// ClearTotpSecret clears the value of the "totp_secret" field.
func (_u *UserUpdateOne) ClearTotpSecret() *UserUpdateOne {
	_u.mutation.ClearTotpSecret()
	return _u
}

// SetTotpSecretConfirmed sets the "totp_secret_confirmed" field.
func (_u *UserUpdateOne) SetTotpSecretConfirmed(v bool) *UserUpdateOne {
	_u.mutation.SetTotpSecretConfirmed(v)
	return _u
}

// SetNillableTotpSecretConfirmed sets the "totp_secret_confirmed" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTotpSecretConfirmed(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetTotpSecretConfirmed(*v)
	}
	return _u
}

// ClearTotpSecretConfirmed clears the value of the "totp_secret_confirmed" field.
func (_u *UserUpdateOne) ClearTotpSecretConfirmed() *UserUpdateOne {
	_u.mutation.ClearTotpSecretConfirmed()
	return _u
}

// SetForgotPasswordCode sets the "forgot_password_code" field.
func (_u *UserUpdateOne) SetForgotPasswordCode(v string) *UserUpdateOne {
	_u.mutation.SetForgotPasswordCode(v)
	return _u
}

// SetNillableForgotPasswordCode sets the "forgot_password_code" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableForgotPasswordCode(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetForgotPasswordCode(*v)
	}
	return _u
}

// ClearForgotPasswordCode clears the value of the "forgot_password_code" field.
func (_u *UserUpdateOne) ClearForgotPasswordCode() *UserUpdateOne {
	_u.mutation.ClearForgotPasswordCode()
	return _u
}

// SetForgotPasswordCodeExpiresAt sets the "forgot_password_code_expires_at" field.
func (_u *UserUpdateOne) SetForgotPasswordCodeExpiresAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetForgotPasswordCodeExpiresAt(v)
	return _u
}

// SetNillableForgotPasswordCodeExpiresAt sets the "forgot_password_code_expires_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableForgotPasswordCodeExpiresAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetForgotPasswordCodeExpiresAt(*v)
	}
	return _u
}

// ClearForgotPasswordCodeExpiresAt clears the value of the "forgot_password_code_expires_at" field.
func (_u *UserUpdateOne) ClearForgotPasswordCodeExpiresAt() *UserUpdateOne {
	_u.mutation.ClearForgotPasswordCodeExpiresAt()
	return _u
}

// SetNewUserToken sets the "new_user_token" field.
func (_u *UserUpdateOne) SetNewUserToken(v string) *UserUpdateOne {
	_u.mutation.SetNewUserToken(v)
	return _u
}

// SetNillableNewUserToken sets the "new_user_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNewUserToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNewUserToken(*v)
	}
	return _u
}

// ClearNewUserToken clears the value of the "new_user_token" field.
func (_u *UserUpdateOne) ClearNewUserToken() *UserUpdateOne {
	_u.mutation.ClearNewUserToken()
	return _u
}

// AddSessionIDs adds the "sessions" edge to the Sessions entity by IDs.
func (_u *UserUpdateOne) AddSessionIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the Sessions entity.
func (_u *UserUpdateOne) AddSessions(v ...*Sessions) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddRecoverycodeIDs adds the "recoverycodes" edge to the RecoveryCode entity by IDs.
func (_u *UserUpdateOne) AddRecoverycodeIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddRecoverycodeIDs(ids...)
	return _u
}

// AddRecoverycodes adds the "recoverycodes" edges to the RecoveryCode entity.
func (_u *UserUpdateOne) AddRecoverycodes(v ...*RecoveryCode) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecoverycodeIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSessions clears all "sessions" edges to the Sessions entity.
func (_u *UserUpdateOne) ClearSessions() *UserUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to Sessions entities by IDs.
func (_u *UserUpdateOne) RemoveSessionIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to Sessions entities.
func (_u *UserUpdateOne) RemoveSessions(v ...*Sessions) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearRecoverycodes clears all "recoverycodes" edges to the RecoveryCode entity.
func (_u *UserUpdateOne) ClearRecoverycodes() *UserUpdateOne {
	_u.mutation.ClearRecoverycodes()
	return _u
}

// RemoveRecoverycodeIDs removes the "recoverycodes" edge to RecoveryCode entities by IDs.
func (_u *UserUpdateOne) RemoveRecoverycodeIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveRecoverycodeIDs(ids...)
	return _u
}

// RemoveRecoverycodes removes "recoverycodes" edges to RecoveryCode entities.
func (_u *UserUpdateOne) RemoveRecoverycodes(v ...*RecoveryCode) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecoverycodeIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.Modified(); !ok && !_u.mutation.ModifiedCleared() {
		v := user.UpdateDefaultModified()
		_u.mutation.SetModified(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(user.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(user.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(user.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Register(); ok {
		_spec.SetField(user.FieldRegister, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertClearPassword(); ok {
		_spec.SetField(user.FieldCertClearPassword, field.TypeString, value)
	}
	if _u.mutation.CertClearPasswordCleared() {
		_spec.ClearField(user.FieldCertClearPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(user.FieldExpiry, field.TypeTime, value)
	}
	if _u.mutation.ExpiryCleared() {
		_spec.ClearField(user.FieldExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.Openid(); ok {
		_spec.SetField(user.FieldOpenid, field.TypeBool, value)
	}
	if _u.mutation.OpenidCleared() {
		_spec.ClearField(user.FieldOpenid, field.TypeBool)
	}
	if value, ok := _u.mutation.Passwd(); ok {
		_spec.SetField(user.FieldPasswd, field.TypeBool, value)
	}
	if _u.mutation.PasswdCleared() {
		_spec.ClearField(user.FieldPasswd, field.TypeBool)
	}
	if value, ok := _u.mutation.Use2fa(); ok {
		_spec.SetField(user.FieldUse2fa, field.TypeBool, value)
	}
	if _u.mutation.Use2faCleared() {
		_spec.ClearField(user.FieldUse2fa, field.TypeBool)
	}
	if value, ok := _u.mutation.Created(); ok {
		_spec.SetField(user.FieldCreated, field.TypeTime, value)
	}
	if _u.mutation.CreatedCleared() {
		_spec.ClearField(user.FieldCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.Modified(); ok {
		_spec.SetField(user.FieldModified, field.TypeTime, value)
	}
	if _u.mutation.ModifiedCleared() {
		_spec.ClearField(user.FieldModified, field.TypeTime)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(user.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(user.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(user.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(user.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.IDToken(); ok {
		_spec.SetField(user.FieldIDToken, field.TypeString, value)
	}
	if _u.mutation.IDTokenCleared() {
		_spec.ClearField(user.FieldIDToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(user.FieldTokenType, field.TypeString, value)
	}
	if _u.mutation.TokenTypeCleared() {
		_spec.ClearField(user.FieldTokenType, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(user.FieldTokenExpiry, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenExpiry(); ok {
		_spec.AddField(user.FieldTokenExpiry, field.TypeInt, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(user.FieldTokenExpiry, field.TypeInt)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(user.FieldHash, field.TypeString, value)
	}
	if _u.mutation.HashCleared() {
		_spec.ClearField(user.FieldHash, field.TypeString)
	}
	if value, ok := _u.mutation.TotpSecret(); ok {
		_spec.SetField(user.FieldTotpSecret, field.TypeString, value)
	}
	if _u.mutation.TotpSecretCleared() {
		_spec.ClearField(user.FieldTotpSecret, field.TypeString)
	}
	if value, ok := _u.mutation.TotpSecretConfirmed(); ok {
		_spec.SetField(user.FieldTotpSecretConfirmed, field.TypeBool, value)
	}
	if _u.mutation.TotpSecretConfirmedCleared() {
		_spec.ClearField(user.FieldTotpSecretConfirmed, field.TypeBool)
	}
	if value, ok := _u.mutation.ForgotPasswordCode(); ok {
		_spec.SetField(user.FieldForgotPasswordCode, field.TypeString, value)
	}
	if _u.mutation.ForgotPasswordCodeCleared() {
		_spec.ClearField(user.FieldForgotPasswordCode, field.TypeString)
	}
	if value, ok := _u.mutation.ForgotPasswordCodeExpiresAt(); ok {
		_spec.SetField(user.FieldForgotPasswordCodeExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ForgotPasswordCodeExpiresAtCleared() {
		_spec.ClearField(user.FieldForgotPasswordCodeExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NewUserToken(); ok {
		_spec.SetField(user.FieldNewUserToken, field.TypeString, value)
	}
	if _u.mutation.NewUserTokenCleared() {
		_spec.ClearField(user.FieldNewUserToken, field.TypeString)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessions.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessions.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessions.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecoverycodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecoverycodesTable,
			Columns: []string{user.RecoverycodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverycode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecoverycodesIDs(); len(nodes) > 0 && !_u.mutation.RecoverycodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecoverycodesTable,
			Columns: []string{user.RecoverycodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverycode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecoverycodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecoverycodesTable,
			Columns: []string{user.RecoverycodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recoverycode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
