// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/tenant"
	"github.com/open-uem/ent/user"
	"github.com/open-uem/ent/usertenant"
)

// UserTenantUpdate is the builder for updating UserTenant entities.
type UserTenantUpdate struct {
	config
	hooks     []Hook
	mutation  *UserTenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserTenantUpdate builder.
func (utu *UserTenantUpdate) Where(ps ...predicate.UserTenant) *UserTenantUpdate {
	utu.mutation.Where(ps...)
	return utu
}

// SetUserID sets the "user_id" field.
func (utu *UserTenantUpdate) SetUserID(s string) *UserTenantUpdate {
	utu.mutation.SetUserID(s)
	return utu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (utu *UserTenantUpdate) SetNillableUserID(s *string) *UserTenantUpdate {
	if s != nil {
		utu.SetUserID(*s)
	}
	return utu
}

// SetTenantID sets the "tenant_id" field.
func (utu *UserTenantUpdate) SetTenantID(i int) *UserTenantUpdate {
	utu.mutation.SetTenantID(i)
	return utu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (utu *UserTenantUpdate) SetNillableTenantID(i *int) *UserTenantUpdate {
	if i != nil {
		utu.SetTenantID(*i)
	}
	return utu
}

// SetRole sets the "role" field.
func (utu *UserTenantUpdate) SetRole(u usertenant.Role) *UserTenantUpdate {
	utu.mutation.SetRole(u)
	return utu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (utu *UserTenantUpdate) SetNillableRole(u *usertenant.Role) *UserTenantUpdate {
	if u != nil {
		utu.SetRole(*u)
	}
	return utu
}

// SetIsDefault sets the "is_default" field.
func (utu *UserTenantUpdate) SetIsDefault(b bool) *UserTenantUpdate {
	utu.mutation.SetIsDefault(b)
	return utu
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (utu *UserTenantUpdate) SetNillableIsDefault(b *bool) *UserTenantUpdate {
	if b != nil {
		utu.SetIsDefault(*b)
	}
	return utu
}

// SetCreated sets the "created" field.
func (utu *UserTenantUpdate) SetCreated(t time.Time) *UserTenantUpdate {
	utu.mutation.SetCreated(t)
	return utu
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (utu *UserTenantUpdate) SetNillableCreated(t *time.Time) *UserTenantUpdate {
	if t != nil {
		utu.SetCreated(*t)
	}
	return utu
}

// ClearCreated clears the value of the "created" field.
func (utu *UserTenantUpdate) ClearCreated() *UserTenantUpdate {
	utu.mutation.ClearCreated()
	return utu
}

// SetModified sets the "modified" field.
func (utu *UserTenantUpdate) SetModified(t time.Time) *UserTenantUpdate {
	utu.mutation.SetModified(t)
	return utu
}

// ClearModified clears the value of the "modified" field.
func (utu *UserTenantUpdate) ClearModified() *UserTenantUpdate {
	utu.mutation.ClearModified()
	return utu
}

// SetUser sets the "user" edge to the User entity.
func (utu *UserTenantUpdate) SetUser(u *User) *UserTenantUpdate {
	return utu.SetUserID(u.ID)
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (utu *UserTenantUpdate) SetTenant(t *Tenant) *UserTenantUpdate {
	return utu.SetTenantID(t.ID)
}

// Mutation returns the UserTenantMutation object of the builder.
func (utu *UserTenantUpdate) Mutation() *UserTenantMutation {
	return utu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (utu *UserTenantUpdate) ClearUser() *UserTenantUpdate {
	utu.mutation.ClearUser()
	return utu
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (utu *UserTenantUpdate) ClearTenant() *UserTenantUpdate {
	utu.mutation.ClearTenant()
	return utu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (utu *UserTenantUpdate) Save(ctx context.Context) (int, error) {
	utu.defaults()
	return withHooks(ctx, utu.sqlSave, utu.mutation, utu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (utu *UserTenantUpdate) SaveX(ctx context.Context) int {
	affected, err := utu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (utu *UserTenantUpdate) Exec(ctx context.Context) error {
	_, err := utu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utu *UserTenantUpdate) ExecX(ctx context.Context) {
	if err := utu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (utu *UserTenantUpdate) defaults() {
	if _, ok := utu.mutation.Modified(); !ok && !utu.mutation.ModifiedCleared() {
		v := usertenant.UpdateDefaultModified()
		utu.mutation.SetModified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (utu *UserTenantUpdate) check() error {
	if v, ok := utu.mutation.UserID(); ok {
		if err := usertenant.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserTenant.user_id": %w`, err)}
		}
	}
	if v, ok := utu.mutation.Role(); ok {
		if err := usertenant.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "UserTenant.role": %w`, err)}
		}
	}
	if utu.mutation.UserCleared() && len(utu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTenant.user"`)
	}
	if utu.mutation.TenantCleared() && len(utu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTenant.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (utu *UserTenantUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserTenantUpdate {
	utu.modifiers = append(utu.modifiers, modifiers...)
	return utu
}

func (utu *UserTenantUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := utu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertenant.Table, usertenant.Columns, sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt))
	if ps := utu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := utu.mutation.Role(); ok {
		_spec.SetField(usertenant.FieldRole, field.TypeEnum, value)
	}
	if value, ok := utu.mutation.IsDefault(); ok {
		_spec.SetField(usertenant.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := utu.mutation.Created(); ok {
		_spec.SetField(usertenant.FieldCreated, field.TypeTime, value)
	}
	if utu.mutation.CreatedCleared() {
		_spec.ClearField(usertenant.FieldCreated, field.TypeTime)
	}
	if value, ok := utu.mutation.Modified(); ok {
		_spec.SetField(usertenant.FieldModified, field.TypeTime, value)
	}
	if utu.mutation.ModifiedCleared() {
		_spec.ClearField(usertenant.FieldModified, field.TypeTime)
	}
	if utu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.UserTable,
			Columns: []string{usertenant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.UserTable,
			Columns: []string{usertenant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if utu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.TenantTable,
			Columns: []string{usertenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.TenantTable,
			Columns: []string{usertenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(utu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, utu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	utu.mutation.done = true
	return n, nil
}

// UserTenantUpdateOne is the builder for updating a single UserTenant entity.
type UserTenantUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserTenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (utuo *UserTenantUpdateOne) SetUserID(s string) *UserTenantUpdateOne {
	utuo.mutation.SetUserID(s)
	return utuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (utuo *UserTenantUpdateOne) SetNillableUserID(s *string) *UserTenantUpdateOne {
	if s != nil {
		utuo.SetUserID(*s)
	}
	return utuo
}

// SetTenantID sets the "tenant_id" field.
func (utuo *UserTenantUpdateOne) SetTenantID(i int) *UserTenantUpdateOne {
	utuo.mutation.SetTenantID(i)
	return utuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (utuo *UserTenantUpdateOne) SetNillableTenantID(i *int) *UserTenantUpdateOne {
	if i != nil {
		utuo.SetTenantID(*i)
	}
	return utuo
}

// SetRole sets the "role" field.
func (utuo *UserTenantUpdateOne) SetRole(u usertenant.Role) *UserTenantUpdateOne {
	utuo.mutation.SetRole(u)
	return utuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (utuo *UserTenantUpdateOne) SetNillableRole(u *usertenant.Role) *UserTenantUpdateOne {
	if u != nil {
		utuo.SetRole(*u)
	}
	return utuo
}

// SetIsDefault sets the "is_default" field.
func (utuo *UserTenantUpdateOne) SetIsDefault(b bool) *UserTenantUpdateOne {
	utuo.mutation.SetIsDefault(b)
	return utuo
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (utuo *UserTenantUpdateOne) SetNillableIsDefault(b *bool) *UserTenantUpdateOne {
	if b != nil {
		utuo.SetIsDefault(*b)
	}
	return utuo
}

// SetCreated sets the "created" field.
func (utuo *UserTenantUpdateOne) SetCreated(t time.Time) *UserTenantUpdateOne {
	utuo.mutation.SetCreated(t)
	return utuo
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (utuo *UserTenantUpdateOne) SetNillableCreated(t *time.Time) *UserTenantUpdateOne {
	if t != nil {
		utuo.SetCreated(*t)
	}
	return utuo
}

// ClearCreated clears the value of the "created" field.
func (utuo *UserTenantUpdateOne) ClearCreated() *UserTenantUpdateOne {
	utuo.mutation.ClearCreated()
	return utuo
}

// SetModified sets the "modified" field.
func (utuo *UserTenantUpdateOne) SetModified(t time.Time) *UserTenantUpdateOne {
	utuo.mutation.SetModified(t)
	return utuo
}

// ClearModified clears the value of the "modified" field.
func (utuo *UserTenantUpdateOne) ClearModified() *UserTenantUpdateOne {
	utuo.mutation.ClearModified()
	return utuo
}

// SetUser sets the "user" edge to the User entity.
func (utuo *UserTenantUpdateOne) SetUser(u *User) *UserTenantUpdateOne {
	return utuo.SetUserID(u.ID)
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (utuo *UserTenantUpdateOne) SetTenant(t *Tenant) *UserTenantUpdateOne {
	return utuo.SetTenantID(t.ID)
}

// Mutation returns the UserTenantMutation object of the builder.
func (utuo *UserTenantUpdateOne) Mutation() *UserTenantMutation {
	return utuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (utuo *UserTenantUpdateOne) ClearUser() *UserTenantUpdateOne {
	utuo.mutation.ClearUser()
	return utuo
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (utuo *UserTenantUpdateOne) ClearTenant() *UserTenantUpdateOne {
	utuo.mutation.ClearTenant()
	return utuo
}

// Where appends a list predicates to the UserTenantUpdate builder.
func (utuo *UserTenantUpdateOne) Where(ps ...predicate.UserTenant) *UserTenantUpdateOne {
	utuo.mutation.Where(ps...)
	return utuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (utuo *UserTenantUpdateOne) Select(field string, fields ...string) *UserTenantUpdateOne {
	utuo.fields = append([]string{field}, fields...)
	return utuo
}

// Save executes the query and returns the updated UserTenant entity.
func (utuo *UserTenantUpdateOne) Save(ctx context.Context) (*UserTenant, error) {
	utuo.defaults()
	return withHooks(ctx, utuo.sqlSave, utuo.mutation, utuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (utuo *UserTenantUpdateOne) SaveX(ctx context.Context) *UserTenant {
	node, err := utuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (utuo *UserTenantUpdateOne) Exec(ctx context.Context) error {
	_, err := utuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utuo *UserTenantUpdateOne) ExecX(ctx context.Context) {
	if err := utuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (utuo *UserTenantUpdateOne) defaults() {
	if _, ok := utuo.mutation.Modified(); !ok && !utuo.mutation.ModifiedCleared() {
		v := usertenant.UpdateDefaultModified()
		utuo.mutation.SetModified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (utuo *UserTenantUpdateOne) check() error {
	if v, ok := utuo.mutation.UserID(); ok {
		if err := usertenant.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserTenant.user_id": %w`, err)}
		}
	}
	if v, ok := utuo.mutation.Role(); ok {
		if err := usertenant.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "UserTenant.role": %w`, err)}
		}
	}
	if utuo.mutation.UserCleared() && len(utuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTenant.user"`)
	}
	if utuo.mutation.TenantCleared() && len(utuo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTenant.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (utuo *UserTenantUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserTenantUpdateOne {
	utuo.modifiers = append(utuo.modifiers, modifiers...)
	return utuo
}

func (utuo *UserTenantUpdateOne) sqlSave(ctx context.Context) (_node *UserTenant, err error) {
	if err := utuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usertenant.Table, usertenant.Columns, sqlgraph.NewFieldSpec(usertenant.FieldID, field.TypeInt))
	id, ok := utuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserTenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := utuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertenant.FieldID)
		for _, f := range fields {
			if !usertenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := utuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := utuo.mutation.Role(); ok {
		_spec.SetField(usertenant.FieldRole, field.TypeEnum, value)
	}
	if value, ok := utuo.mutation.IsDefault(); ok {
		_spec.SetField(usertenant.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := utuo.mutation.Created(); ok {
		_spec.SetField(usertenant.FieldCreated, field.TypeTime, value)
	}
	if utuo.mutation.CreatedCleared() {
		_spec.ClearField(usertenant.FieldCreated, field.TypeTime)
	}
	if value, ok := utuo.mutation.Modified(); ok {
		_spec.SetField(usertenant.FieldModified, field.TypeTime, value)
	}
	if utuo.mutation.ModifiedCleared() {
		_spec.ClearField(usertenant.FieldModified, field.TypeTime)
	}
	if utuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.UserTable,
			Columns: []string{usertenant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.UserTable,
			Columns: []string{usertenant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if utuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.TenantTable,
			Columns: []string{usertenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utuo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usertenant.TenantTable,
			Columns: []string{usertenant.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(utuo.modifiers...)
	_node = &UserTenant{config: utuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, utuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	utuo.mutation.done = true
	return _node, nil
}
