// Code generated by ent, DO NOT EDIT.

package netbird

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the netbird type in the database.
	Label = "netbird"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldInstalled holds the string denoting the installed field in the database.
	FieldInstalled = "installed"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldProfile holds the string denoting the profile field in the database.
	FieldProfile = "profile"
	// FieldManagementURL holds the string denoting the management_url field in the database.
	FieldManagementURL = "management_url"
	// FieldManagementConnected holds the string denoting the management_connected field in the database.
	FieldManagementConnected = "management_connected"
	// FieldSSHEnabled holds the string denoting the ssh_enabled field in the database.
	FieldSSHEnabled = "ssh_enabled"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// AgentFieldID holds the string denoting the ID field of the Agent.
	AgentFieldID = "oid"
	// Table holds the table name of the netbird in the database.
	Table = "netbirds"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "netbirds"
	// OwnerInverseTable is the table name for the Agent entity.
	// It exists in this package in order to avoid circular dependency with the "agent" package.
	OwnerInverseTable = "agents"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "agent_netbird"
)

// Columns holds all SQL columns for netbird fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldInstalled,
	FieldIP,
	FieldProfile,
	FieldManagementURL,
	FieldManagementConnected,
	FieldSSHEnabled,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "netbirds"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"agent_netbird",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion string
	// DefaultInstalled holds the default value on creation for the "installed" field.
	DefaultInstalled bool
	// DefaultIP holds the default value on creation for the "ip" field.
	DefaultIP string
	// DefaultProfile holds the default value on creation for the "profile" field.
	DefaultProfile string
	// DefaultManagementURL holds the default value on creation for the "management_url" field.
	DefaultManagementURL string
	// DefaultManagementConnected holds the default value on creation for the "management_connected" field.
	DefaultManagementConnected bool
	// DefaultSSHEnabled holds the default value on creation for the "ssh_enabled" field.
	DefaultSSHEnabled bool
)

// OrderOption defines the ordering options for the Netbird queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByInstalled orders the results by the installed field.
func ByInstalled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalled, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByProfile orders the results by the profile field.
func ByProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfile, opts...).ToFunc()
}

// ByManagementURL orders the results by the management_url field.
func ByManagementURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagementURL, opts...).ToFunc()
}

// ByManagementConnected orders the results by the management_connected field.
func ByManagementConnected(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagementConnected, opts...).ToFunc()
}

// BySSHEnabled orders the results by the ssh_enabled field.
func BySSHEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHEnabled, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, AgentFieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
	)
}
